<?php

declare(strict_types=1);

/**
 * AccountExportsApi
 * PHP version 5.
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mailchimp Marketing API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.80
 * Contact: apihelp@mailchimp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MailchimpMarketing\Api;

use GuzzleHttp\Psr7\Request;

class AccountExportsApi extends AbstractApi
{
    public function listAccountExports($fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        return $this->listAccountExportsWithHttpInfo($fields, $exclude_fields, $count, $offset);
    }

    public function listAccountExportsWithHttpInfo($fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        $request = $this->listAccountExportsRequest($fields, $exclude_fields, $count, $offset);

        return $this->sendRequest($request);
    }

    public function createAccountExport($body)
    {
        return $this->createAccountExportWithHttpInfo($body);
    }

    public function createAccountExportWithHttpInfo($body)
    {
        $request = $this->createAccountExportRequest($body);

        return $this->sendRequest($request);
    }

    protected function listAccountExportsRequest($fields = null, $exclude_fields = null, $count = '10', $offset = '0'): Request
    {
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling AccountExportsApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/account-exports';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function createAccountExportRequest($body): Request
    {
        $this->requireParam($body, 'body');

        $resourcePath = '/account-exports';
        $queryParams = [];

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }
}
