<?php

declare(strict_types=1);

/**
 * ActivityFeedApi
 * PHP version 5.
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mailchimp Marketing API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.80
 * Contact: apihelp@mailchimp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MailchimpMarketing\Api;

use GuzzleHttp\Psr7\Request;

class ActivityFeedApi extends AbstractApi
{
    public function getChimpChatter($count = '10', $offset = '0')
    {
        return $this->getChimpChatterWithHttpInfo($count, $offset);
    }

    public function getChimpChatterWithHttpInfo($count = '10', $offset = '0')
    {
        $request = $this->getChimpChatterRequest($count, $offset);

        return $this->sendRequest($request);
    }

    protected function getChimpChatterRequest($count = '10', $offset = '0'): Request
    {
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ActivityFeedApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/activity-feed/chimp-chatter';
        $queryParams = [];
        $this->addQueryParam($queryParams, 'count', $count);
        $this->addQueryParam($queryParams, 'offset', $offset);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }
}
