<?php

declare(strict_types=1);

/**
 * AuthorizedAppsApi
 * PHP version 5.
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mailchimp Marketing API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.80
 * Contact: apihelp@mailchimp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MailchimpMarketing\Api;

use GuzzleHttp\Psr7\Request;

class AuthorizedAppsApi extends AbstractApi
{
    public function list($fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        return $this->listWithHttpInfo($fields, $exclude_fields, $count, $offset);
    }

    public function listWithHttpInfo($fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        $request = $this->listRequest($fields, $exclude_fields, $count, $offset);

        return $this->sendRequest($request);
    }

    public function get($app_id, $fields = null, $exclude_fields = null)
    {
        return $this->getWithHttpInfo($app_id, $fields, $exclude_fields);
    }

    public function getWithHttpInfo($app_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getRequest($app_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    protected function listRequest($fields = null, $exclude_fields = null, $count = '10', $offset = '0'): Request
    {
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling AuthorizedAppsApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/authorized-apps';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getRequest($app_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($app_id, 'app_id');

        $resourcePath = '/authorized-apps/{app_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'app_id', $app_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }
}
