<?php

declare(strict_types=1);

/**
 * AutomationsApi
 * PHP version 5.
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mailchimp Marketing API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.80
 * Contact: apihelp@mailchimp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MailchimpMarketing\Api;

use GuzzleHttp\Psr7\Request;

class AutomationsApi extends AbstractApi
{
    public function archive($workflow_id): void
    {
        $this->archiveWithHttpInfo($workflow_id);
    }

    public function archiveWithHttpInfo($workflow_id)
    {
        $request = $this->archiveRequest($workflow_id);

        return $this->sendRequest($request);
    }

    public function deleteWorkflowEmail($workflow_id, $workflow_email_id): void
    {
        $this->deleteWorkflowEmailWithHttpInfo($workflow_id, $workflow_email_id);
    }

    public function deleteWorkflowEmailWithHttpInfo($workflow_id, $workflow_email_id)
    {
        $request = $this->deleteWorkflowEmailRequest($workflow_id, $workflow_email_id);

        return $this->sendRequest($request);
    }

    public function list($count = '10', $offset = '0', $fields = null, $exclude_fields = null, $before_create_time = null, $since_create_time = null, $before_start_time = null, $since_start_time = null, $status = null)
    {
        return $this->listWithHttpInfo($count, $offset, $fields, $exclude_fields, $before_create_time, $since_create_time, $before_start_time, $since_start_time, $status);
    }

    public function listWithHttpInfo($count = '10', $offset = '0', $fields = null, $exclude_fields = null, $before_create_time = null, $since_create_time = null, $before_start_time = null, $since_start_time = null, $status = null)
    {
        $request = $this->listRequest($count, $offset, $fields, $exclude_fields, $before_create_time, $since_create_time, $before_start_time, $since_start_time, $status);

        return $this->sendRequest($request);
    }

    public function get($workflow_id, $fields = null, $exclude_fields = null)
    {
        return $this->getWithHttpInfo($workflow_id, $fields, $exclude_fields);
    }

    public function getWithHttpInfo($workflow_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getRequest($workflow_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function listAllWorkflowEmails($workflow_id)
    {
        return $this->listAllWorkflowEmailsWithHttpInfo($workflow_id);
    }

    public function listAllWorkflowEmailsWithHttpInfo($workflow_id)
    {
        $request = $this->listAllWorkflowEmailsRequest($workflow_id);

        return $this->sendRequest($request);
    }

    public function getWorkflowEmail($workflow_id, $workflow_email_id)
    {
        return $this->getWorkflowEmailWithHttpInfo($workflow_id, $workflow_email_id);
    }

    public function getWorkflowEmailWithHttpInfo($workflow_id, $workflow_email_id)
    {
        $request = $this->getWorkflowEmailRequest($workflow_id, $workflow_email_id);

        return $this->sendRequest($request);
    }

    public function getWorkflowEmailSubscriberQueue($workflow_id, $workflow_email_id)
    {
        return $this->getWorkflowEmailSubscriberQueueWithHttpInfo($workflow_id, $workflow_email_id);
    }

    public function getWorkflowEmailSubscriberQueueWithHttpInfo($workflow_id, $workflow_email_id)
    {
        $request = $this->getWorkflowEmailSubscriberQueueRequest($workflow_id, $workflow_email_id);

        return $this->sendRequest($request);
    }

    public function getWorkflowEmailSubscriber($workflow_id, $workflow_email_id, $subscriber_hash)
    {
        return $this->getWorkflowEmailSubscriberWithHttpInfo($workflow_id, $workflow_email_id, $subscriber_hash);
    }

    public function getWorkflowEmailSubscriberWithHttpInfo($workflow_id, $workflow_email_id, $subscriber_hash)
    {
        $request = $this->getWorkflowEmailSubscriberRequest($workflow_id, $workflow_email_id, $subscriber_hash);

        return $this->sendRequest($request);
    }

    public function listWorkflowEmailSubscribersRemoved($workflow_id)
    {
        return $this->listWorkflowEmailSubscribersRemovedWithHttpInfo($workflow_id);
    }

    public function listWorkflowEmailSubscribersRemovedWithHttpInfo($workflow_id)
    {
        $request = $this->listWorkflowEmailSubscribersRemovedRequest($workflow_id);

        return $this->sendRequest($request);
    }

    public function getRemovedWorkflowEmailSubscriber($workflow_id, $subscriber_hash)
    {
        return $this->getRemovedWorkflowEmailSubscriberWithHttpInfo($workflow_id, $subscriber_hash);
    }

    public function getRemovedWorkflowEmailSubscriberWithHttpInfo($workflow_id, $subscriber_hash)
    {
        $request = $this->getRemovedWorkflowEmailSubscriberRequest($workflow_id, $subscriber_hash);

        return $this->sendRequest($request);
    }

    public function updateWorkflowEmail($workflow_id, $workflow_email_id, $body)
    {
        return $this->updateWorkflowEmailWithHttpInfo($workflow_id, $workflow_email_id, $body);
    }

    public function updateWorkflowEmailWithHttpInfo($workflow_id, $workflow_email_id, $body)
    {
        $request = $this->updateWorkflowEmailRequest($workflow_id, $workflow_email_id, $body);

        return $this->sendRequest($request);
    }

    public function create($body)
    {
        return $this->createWithHttpInfo($body);
    }

    public function createWithHttpInfo($body)
    {
        $request = $this->createRequest($body);

        return $this->sendRequest($request);
    }

    public function pauseAllEmails($workflow_id): void
    {
        $this->pauseAllEmailsWithHttpInfo($workflow_id);
    }

    public function pauseAllEmailsWithHttpInfo($workflow_id)
    {
        $request = $this->pauseAllEmailsRequest($workflow_id);

        return $this->sendRequest($request);
    }

    public function startAllEmails($workflow_id): void
    {
        $this->startAllEmailsWithHttpInfo($workflow_id);
    }

    public function startAllEmailsWithHttpInfo($workflow_id)
    {
        $request = $this->startAllEmailsRequest($workflow_id);

        return $this->sendRequest($request);
    }

    public function pauseWorkflowEmail($workflow_id, $workflow_email_id): void
    {
        $this->pauseWorkflowEmailWithHttpInfo($workflow_id, $workflow_email_id);
    }

    public function pauseWorkflowEmailWithHttpInfo($workflow_id, $workflow_email_id)
    {
        $request = $this->pauseWorkflowEmailRequest($workflow_id, $workflow_email_id);

        return $this->sendRequest($request);
    }

    public function startWorkflowEmail($workflow_id, $workflow_email_id): void
    {
        $this->startWorkflowEmailWithHttpInfo($workflow_id, $workflow_email_id);
    }

    public function startWorkflowEmailWithHttpInfo($workflow_id, $workflow_email_id)
    {
        $request = $this->startWorkflowEmailRequest($workflow_id, $workflow_email_id);

        return $this->sendRequest($request);
    }

    public function addWorkflowEmailSubscriber($workflow_id, $workflow_email_id, $body)
    {
        return $this->addWorkflowEmailSubscriberWithHttpInfo($workflow_id, $workflow_email_id, $body);
    }

    public function addWorkflowEmailSubscriberWithHttpInfo($workflow_id, $workflow_email_id, $body)
    {
        $request = $this->addWorkflowEmailSubscriberRequest($workflow_id, $workflow_email_id, $body);

        return $this->sendRequest($request);
    }

    public function removeWorkflowEmailSubscriber($workflow_id, $body)
    {
        return $this->removeWorkflowEmailSubscriberWithHttpInfo($workflow_id, $body);
    }

    public function removeWorkflowEmailSubscriberWithHttpInfo($workflow_id, $body)
    {
        $request = $this->removeWorkflowEmailSubscriberRequest($workflow_id, $body);

        return $this->sendRequest($request);
    }

    protected function archiveRequest($workflow_id): Request
    {
        $this->requireParam($workflow_id, 'workflow_id');

        $resourcePath = '/automations/{workflow_id}/actions/archive';
        $queryParams = [];
        $this->replacePathParam($resourcePath, 'workflow_id', $workflow_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams);
    }

    protected function deleteWorkflowEmailRequest($workflow_id, $workflow_email_id): Request
    {
        $this->requireParam($workflow_id, 'workflow_id');
        $this->requireParam($workflow_email_id, 'workflow_email_id');

        $resourcePath = '/automations/{workflow_id}/emails/{workflow_email_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'workflow_id', $workflow_id);
        $this->replacePathParam($resourcePath, 'workflow_email_id', $workflow_email_id);

        return $this->buildRequest('DELETE', $resourcePath, $queryParams);
    }

    protected function listRequest($count = '10', $offset = '0', $fields = null, $exclude_fields = null, $before_create_time = null, $since_create_time = null, $before_start_time = null, $since_start_time = null, $status = null): Request
    {
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling AutomationsApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/automations';
        $queryParams = [];
        $this->addQueryParam($queryParams, 'count', $count);
        $this->addQueryParam($queryParams, 'offset', $offset);
        $this->addQueryParam($queryParams, 'fields', $fields);
        $this->addQueryParam($queryParams, 'exclude_fields', $exclude_fields);
        $this->addQueryParam($queryParams, 'before_create_time', $before_create_time);
        $this->addQueryParam($queryParams, 'since_create_time', $since_create_time);
        $this->addQueryParam($queryParams, 'before_start_time', $before_start_time);
        $this->addQueryParam($queryParams, 'since_start_time', $since_start_time);
        $this->addQueryParam($queryParams, 'status', $status);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getRequest($workflow_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($workflow_id, 'workflow_id');

        $resourcePath = '/automations/{workflow_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'workflow_id', $workflow_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function listAllWorkflowEmailsRequest($workflow_id): Request
    {
        $this->requireParam($workflow_id, 'workflow_id');

        $resourcePath = '/automations/{workflow_id}/emails';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'workflow_id', $workflow_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getWorkflowEmailRequest($workflow_id, $workflow_email_id): Request
    {
        $this->requireParam($workflow_id, 'workflow_id');
        $this->requireParam($workflow_email_id, 'workflow_email_id');

        $resourcePath = '/automations/{workflow_id}/emails/{workflow_email_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'workflow_id', $workflow_id);
        $this->replacePathParam($resourcePath, 'workflow_email_id', $workflow_email_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getWorkflowEmailSubscriberQueueRequest($workflow_id, $workflow_email_id): Request
    {
        $this->requireParam($workflow_id, 'workflow_id');
        $this->requireParam($workflow_email_id, 'workflow_email_id');

        $resourcePath = '/automations/{workflow_id}/emails/{workflow_email_id}/queue';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'workflow_id', $workflow_id);
        $this->replacePathParam($resourcePath, 'workflow_email_id', $workflow_email_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getWorkflowEmailSubscriberRequest($workflow_id, $workflow_email_id, $subscriber_hash): Request
    {
        $this->requireParam($workflow_id, 'workflow_id');
        $this->requireParam($workflow_email_id, 'workflow_email_id');
        $this->requireParam($subscriber_hash, 'subscriber_hash');

        $resourcePath = '/automations/{workflow_id}/emails/{workflow_email_id}/queue/{subscriber_hash}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'workflow_id', $workflow_id);
        $this->replacePathParam($resourcePath, 'workflow_email_id', $workflow_email_id);
        $this->replacePathParam($resourcePath, 'subscriber_hash', $subscriber_hash);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function listWorkflowEmailSubscribersRemovedRequest($workflow_id): Request
    {
        $this->requireParam($workflow_id, 'workflow_id');

        $resourcePath = '/automations/{workflow_id}/removed-subscribers';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'workflow_id', $workflow_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getRemovedWorkflowEmailSubscriberRequest($workflow_id, $subscriber_hash): Request
    {
        $this->requireParam($workflow_id, 'workflow_id');
        $this->requireParam($subscriber_hash, 'subscriber_hash');

        $resourcePath = '/automations/{workflow_id}/removed-subscribers/{subscriber_hash}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'workflow_id', $workflow_id);
        $this->replacePathParam($resourcePath, 'subscriber_hash', $subscriber_hash);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function updateWorkflowEmailRequest($workflow_id, $workflow_email_id, $body): Request
    {
        $this->requireParam($workflow_id, 'workflow_id');
        $this->requireParam($workflow_email_id, 'workflow_email_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/automations/{workflow_id}/emails/{workflow_email_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'workflow_id', $workflow_id);
        $this->replacePathParam($resourcePath, 'workflow_email_id', $workflow_email_id);

        return $this->buildRequest('PATCH', $resourcePath, $queryParams, $body);
    }

    protected function createRequest($body): Request
    {
        $this->requireParam($body, 'body');

        $resourcePath = '/automations';
        $queryParams = [];

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function pauseAllEmailsRequest($workflow_id): Request
    {
        $this->requireParam($workflow_id, 'workflow_id');

        $resourcePath = '/automations/{workflow_id}/actions/pause-all-emails';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'workflow_id', $workflow_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams);
    }

    protected function startAllEmailsRequest($workflow_id): Request
    {
        $this->requireParam($workflow_id, 'workflow_id');

        $resourcePath = '/automations/{workflow_id}/actions/start-all-emails';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'workflow_id', $workflow_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams);
    }

    protected function pauseWorkflowEmailRequest($workflow_id, $workflow_email_id): Request
    {
        $this->requireParam($workflow_id, 'workflow_id');
        $this->requireParam($workflow_email_id, 'workflow_email_id');

        $resourcePath = '/automations/{workflow_id}/emails/{workflow_email_id}/actions/pause';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'workflow_id', $workflow_id);
        $this->replacePathParam($resourcePath, 'workflow_email_id', $workflow_email_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams);
    }

    protected function startWorkflowEmailRequest($workflow_id, $workflow_email_id): Request
    {
        $this->requireParam($workflow_id, 'workflow_id');
        $this->requireParam($workflow_email_id, 'workflow_email_id');

        $resourcePath = '/automations/{workflow_id}/emails/{workflow_email_id}/actions/start';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'workflow_id', $workflow_id);
        $this->replacePathParam($resourcePath, 'workflow_email_id', $workflow_email_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams);
    }

    protected function addWorkflowEmailSubscriberRequest($workflow_id, $workflow_email_id, $body): Request
    {
        $this->requireParam($workflow_id, 'workflow_id');
        $this->requireParam($workflow_email_id, 'workflow_email_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/automations/{workflow_id}/emails/{workflow_email_id}/queue';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'workflow_id', $workflow_id);
        $this->replacePathParam($resourcePath, 'workflow_email_id', $workflow_email_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function removeWorkflowEmailSubscriberRequest($workflow_id, $body): Request
    {
        $this->requireParam($workflow_id, 'workflow_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/automations/{workflow_id}/removed-subscribers';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'workflow_id', $workflow_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }
}
