<?php

declare(strict_types=1);

/**
 * BatchWebhooksApi
 * PHP version 5.
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mailchimp Marketing API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.80
 * Contact: apihelp@mailchimp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MailchimpMarketing\Api;

use GuzzleHttp\Psr7\Request;
use MailchimpMarketing\ObjectSerializer;

class BatchWebhooksApi extends AbstractApi
{
    public function remove($batch_webhook_id): void
    {
        $this->removeWithHttpInfo($batch_webhook_id);
    }

    public function removeWithHttpInfo($batch_webhook_id)
    {
        $request = $this->removeRequest($batch_webhook_id);

        return $this->sendRequest($request);
    }

    public function get($batch_webhook_id, $fields = null, $exclude_fields = null)
    {
        return $this->getWithHttpInfo($batch_webhook_id, $fields, $exclude_fields);
    }

    public function getWithHttpInfo($batch_webhook_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getRequest($batch_webhook_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function list($fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        return $this->listWithHttpInfo($fields, $exclude_fields, $count, $offset);
    }

    public function listWithHttpInfo($fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        $request = $this->listRequest($fields, $exclude_fields, $count, $offset);

        return $this->sendRequest($request);
    }

    public function update($batch_webhook_id, $body)
    {
        return $this->updateWithHttpInfo($batch_webhook_id, $body);
    }

    public function updateWithHttpInfo($batch_webhook_id, $body)
    {
        $request = $this->updateRequest($batch_webhook_id, $body);

        return $this->sendRequest($request);
    }

    public function create($body)
    {
        return $this->createWithHttpInfo($body);
    }

    public function createWithHttpInfo($body)
    {
        $request = $this->createRequest($body);

        return $this->sendRequest($request);
    }

    protected function removeRequest($batch_webhook_id): Request
    {
        $this->requireParam($batch_webhook_id, 'batch_webhook_id');

        $resourcePath = '/batch-webhooks/{batch_webhook_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'batch_webhook_id', $batch_webhook_id);

        return $this->buildRequest('DELETE', $resourcePath, $queryParams);
    }

    protected function getRequest($batch_webhook_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($batch_webhook_id, 'batch_webhook_id');

        $resourcePath = '/batch-webhooks/{batch_webhook_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'batch_webhook_id', $batch_webhook_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function listRequest($fields = null, $exclude_fields = null, $count = '10', $offset = '0'): Request
    {
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling BatchWebhooksApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/batch-webhooks';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function updateRequest($batch_webhook_id, $body): Request
    {
        $this->requireParam($batch_webhook_id, 'batch_webhook_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/batch-webhooks/{batch_webhook_id}';
        $queryParams = [];

        // path params
        $resourcePath = str_replace(
            '{batch_webhook_id}',
            ObjectSerializer::toPathValue($batch_webhook_id),
            $resourcePath
        );

        return $this->buildRequest('PATCH', $resourcePath, $queryParams, $body);
    }

    protected function createRequest($body): Request
    {
        $this->requireParam($body, 'body');

        $resourcePath = '/batch-webhooks';
        $queryParams = [];

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }
}
