<?php

declare(strict_types=1);

/**
 * BatchesApi
 * PHP version 5.
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mailchimp Marketing API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.80
 * Contact: apihelp@mailchimp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MailchimpMarketing\Api;

use GuzzleHttp\Psr7\Request;

class BatchesApi extends AbstractApi
{
    public function deleteRequest($batch_id): void
    {
        $this->deleteRequestWithHttpInfo($batch_id);
    }

    public function deleteRequestWithHttpInfo($batch_id)
    {
        $request = $this->deleteRequestRequest($batch_id);

        return $this->sendRequest($request);
    }

    public function list($fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        return $this->listWithHttpInfo($fields, $exclude_fields, $count, $offset);
    }

    public function listWithHttpInfo($fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        $request = $this->listRequest($fields, $exclude_fields, $count, $offset);

        return $this->sendRequest($request);
    }

    public function status($batch_id, $fields = null, $exclude_fields = null)
    {
        return $this->statusWithHttpInfo($batch_id, $fields, $exclude_fields);
    }

    public function statusWithHttpInfo($batch_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->statusRequest($batch_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function start($body)
    {
        return $this->startWithHttpInfo($body);
    }

    public function startWithHttpInfo($body)
    {
        $request = $this->startRequest($body);

        return $this->sendRequest($request);
    }

    protected function deleteRequestRequest($batch_id): Request
    {
        $this->requireParam($batch_id, 'batch_id');

        $resourcePath = '/batches/{batch_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'batch_id', $batch_id);

        return $this->buildRequest('DELETE', $resourcePath, $queryParams);
    }

    protected function listRequest($fields = null, $exclude_fields = null, $count = '10', $offset = '0'): Request
    {
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling BatchesApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/batches';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function statusRequest($batch_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($batch_id, 'batch_id');

        $resourcePath = '/batches/{batch_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'batch_id', $batch_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function startRequest($body): Request
    {
        $this->requireParam($body, 'body');

        $resourcePath = '/batches';
        $queryParams = [];

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }
}
