<?php

declare(strict_types=1);

/**
 * CampaignsApi
 * PHP version 5.
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mailchimp Marketing API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.80
 * Contact: apihelp@mailchimp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MailchimpMarketing\Api;

use GuzzleHttp\Psr7\Request;

class CampaignsApi extends AbstractApi
{
    public function remove($campaign_id): void
    {
        $this->removeWithHttpInfo($campaign_id);
    }

    public function removeWithHttpInfo($campaign_id): Request
    {
        $request = $this->removeRequest($campaign_id);

        return $this->sendRequest($request);
    }

    public function deleteFeedbackMessage($campaign_id, $feedback_id): void
    {
        $this->deleteFeedbackMessageWithHttpInfo($campaign_id, $feedback_id);
    }

    public function deleteFeedbackMessageWithHttpInfo($campaign_id, $feedback_id): Request
    {
        $request = $this->deleteFeedbackMessageRequest($campaign_id, $feedback_id);

        return $this->sendRequest($request);
    }

    public function list($fields = null, $exclude_fields = null, $count = '10', $offset = '0', $type = null, $status = null, $before_send_time = null, $since_send_time = null, $before_create_time = null, $since_create_time = null, $list_id = null, $folder_id = null, $member_id = null, $sort_field = null, $sort_dir = null): Request
    {
        return $this->listWithHttpInfo($fields, $exclude_fields, $count, $offset, $type, $status, $before_send_time, $since_send_time, $before_create_time, $since_create_time, $list_id, $folder_id, $member_id, $sort_field, $sort_dir);
    }

    public function listWithHttpInfo($fields = null, $exclude_fields = null, $count = '10', $offset = '0', $type = null, $status = null, $before_send_time = null, $since_send_time = null, $before_create_time = null, $since_create_time = null, $list_id = null, $folder_id = null, $member_id = null, $sort_field = null, $sort_dir = null): Request
    {
        $request = $this->listRequest($fields, $exclude_fields, $count, $offset, $type, $status, $before_send_time, $since_send_time, $before_create_time, $since_create_time, $list_id, $folder_id, $member_id, $sort_field, $sort_dir);

        return $this->sendRequest($request);
    }

    public function get($campaign_id, $fields = null, $exclude_fields = null): Request
    {
        return $this->getWithHttpInfo($campaign_id, $fields, $exclude_fields);
    }

    public function getWithHttpInfo($campaign_id, $fields = null, $exclude_fields = null): Request
    {
        $request = $this->getRequest($campaign_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getContent($campaign_id, $fields = null, $exclude_fields = null): Request
    {
        return $this->getContentWithHttpInfo($campaign_id, $fields, $exclude_fields);
    }

    public function getContentWithHttpInfo($campaign_id, $fields = null, $exclude_fields = null): Request
    {
        $request = $this->getContentRequest($campaign_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getFeedback($campaign_id, $fields = null, $exclude_fields = null): Request
    {
        return $this->getFeedbackWithHttpInfo($campaign_id, $fields, $exclude_fields);
    }

    public function getFeedbackWithHttpInfo($campaign_id, $fields = null, $exclude_fields = null): Request
    {
        $request = $this->getFeedbackRequest($campaign_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getFeedbackMessage($campaign_id, $feedback_id, $fields = null, $exclude_fields = null): Request
    {
        return $this->getFeedbackMessageWithHttpInfo($campaign_id, $feedback_id, $fields, $exclude_fields);
    }

    public function getFeedbackMessageWithHttpInfo($campaign_id, $feedback_id, $fields = null, $exclude_fields = null): Request
    {
        $request = $this->getFeedbackMessageRequest($campaign_id, $feedback_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getSendChecklist($campaign_id, $fields = null, $exclude_fields = null): Request
    {
        return $this->getSendChecklistWithHttpInfo($campaign_id, $fields, $exclude_fields);
    }

    public function getSendChecklistWithHttpInfo($campaign_id, $fields = null, $exclude_fields = null): Request
    {
        $request = $this->getSendChecklistRequest($campaign_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function update($campaign_id, $body): Request
    {
        return $this->updateWithHttpInfo($campaign_id, $body);
    }

    public function updateWithHttpInfo($campaign_id, $body): Request
    {
        $request = $this->updateRequest($campaign_id, $body);

        return $this->sendRequest($request);
    }

    public function updateFeedbackMessage($campaign_id, $feedback_id, $body): Request
    {
        return $this->updateFeedbackMessageWithHttpInfo($campaign_id, $feedback_id, $body);
    }

    public function updateFeedbackMessageWithHttpInfo($campaign_id, $feedback_id, $body): Request
    {
        $request = $this->updateFeedbackMessageRequest($campaign_id, $feedback_id, $body);

        return $this->sendRequest($request);
    }

    public function create($body): Request
    {
        return $this->createWithHttpInfo($body);
    }

    public function createWithHttpInfo($body): Request
    {
        $request = $this->createRequest($body);

        return $this->sendRequest($request);
    }

    public function cancelSend($campaign_id): void
    {
        $this->cancelSendWithHttpInfo($campaign_id);
    }

    public function cancelSendWithHttpInfo($campaign_id): Request
    {
        $request = $this->cancelSendRequest($campaign_id);

        return $this->sendRequest($request);
    }

    public function createResend($campaign_id): Request
    {
        return $this->createResendWithHttpInfo($campaign_id);
    }

    public function createResendWithHttpInfo($campaign_id): Request
    {
        $request = $this->createResendRequest($campaign_id);

        return $this->sendRequest($request);
    }

    public function pause($campaign_id): void
    {
        $this->pauseWithHttpInfo($campaign_id);
    }

    public function pauseWithHttpInfo($campaign_id): Request
    {
        $request = $this->pauseRequest($campaign_id);

        return $this->sendRequest($request);
    }

    public function replicate($campaign_id): Request
    {
        return $this->replicateWithHttpInfo($campaign_id);
    }

    public function replicateWithHttpInfo($campaign_id): Request
    {
        $request = $this->replicateRequest($campaign_id);

        return $this->sendRequest($request);
    }

    public function resume($campaign_id): void
    {
        $this->resumeWithHttpInfo($campaign_id);
    }

    public function resumeWithHttpInfo($campaign_id): Request
    {
        $request = $this->resumeRequest($campaign_id);

        return $this->sendRequest($request);
    }

    public function schedule($campaign_id, $body): void
    {
        $this->scheduleWithHttpInfo($campaign_id, $body);
    }

    public function scheduleWithHttpInfo($campaign_id, $body): Request
    {
        $request = $this->scheduleRequest($campaign_id, $body);

        return $this->sendRequest($request);
    }

    public function send($campaign_id): void
    {
        $this->sendWithHttpInfo($campaign_id);
    }

    public function sendWithHttpInfo($campaign_id): Request
    {
        $request = $this->sendRequest($campaign_id);

        return $this->sendRequest($request);
    }

    public function sendTestEmail($campaign_id, $body): void
    {
        $this->sendTestEmailWithHttpInfo($campaign_id, $body);
    }

    public function sendTestEmailWithHttpInfo($campaign_id, $body): Request
    {
        $request = $this->sendTestEmailRequest($campaign_id, $body);

        return $this->sendRequest($request);
    }

    public function unschedule($campaign_id): void
    {
        $this->unscheduleWithHttpInfo($campaign_id);
    }

    public function unscheduleWithHttpInfo($campaign_id): Request
    {
        $request = $this->unscheduleRequest($campaign_id);

        return $this->sendRequest($request);
    }

    public function addFeedback($campaign_id, $body): Request
    {
        return $this->addFeedbackWithHttpInfo($campaign_id, $body);
    }

    public function addFeedbackWithHttpInfo($campaign_id, $body): Request
    {
        $request = $this->addFeedbackRequest($campaign_id, $body);

        return $this->sendRequest($request);
    }

    public function setContent($campaign_id, $body): Request
    {
        return $this->setContentWithHttpInfo($campaign_id, $body);
    }

    public function setContentWithHttpInfo($campaign_id, $body): Request
    {
        $request = $this->setContentRequest($campaign_id, $body);

        return $this->sendRequest($request);
    }

    protected function removeRequest($campaign_id): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');

        $resourcePath = '/campaigns/{campaign_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);

        return $this->buildRequest('DELETE', $resourcePath, $queryParams);
    }

    protected function deleteFeedbackMessageRequest($campaign_id, $feedback_id): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');
        $this->requireParam($feedback_id, 'feedback_id');

        $resourcePath = '/campaigns/{campaign_id}/feedback/{feedback_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);
        $this->replacePathParam($resourcePath, 'feedback_id', $feedback_id);

        return $this->buildRequest('DELETE', $resourcePath, $queryParams);
    }

    protected function listRequest($fields = null, $exclude_fields = null, $count = '10', $offset = '0', $type = null, $status = null, $before_send_time = null, $since_send_time = null, $before_create_time = null, $since_create_time = null, $list_id = null, $folder_id = null, $member_id = null, $sort_field = null, $sort_dir = null): Request
    {
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling CampaignsApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/campaigns';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);
        $this->addQueryParam($queryParams, 'type', $type);
        $this->addQueryParam($queryParams, 'status', $status);
        $this->addQueryParam($queryParams, 'before_send_time', $before_send_time);
        $this->addQueryParam($queryParams, 'since_send_time', $since_send_time);
        $this->addQueryParam($queryParams, 'before_create_time', $before_create_time);
        $this->addQueryParam($queryParams, 'since_create_time', $since_create_time);
        $this->addQueryParam($queryParams, 'list_id', $list_id);
        $this->addQueryParam($queryParams, 'folder_id', $folder_id);
        $this->addQueryParam($queryParams, 'member_id', $member_id);
        $this->addQueryParam($queryParams, 'sort_field', $sort_field);
        $this->addQueryParam($queryParams, 'sort_dir', $sort_dir);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getRequest($campaign_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');

        $resourcePath = '/campaigns/{campaign_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getContentRequest($campaign_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');

        $resourcePath = '/campaigns/{campaign_id}/content';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getFeedbackRequest($campaign_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');

        $resourcePath = '/campaigns/{campaign_id}/feedback';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getFeedbackMessageRequest($campaign_id, $feedback_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');
        $this->requireParam($feedback_id, 'feedback_id');

        $resourcePath = '/campaigns/{campaign_id}/feedback/{feedback_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);
        $this->replacePathParam($resourcePath, 'feedback_id', $feedback_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getSendChecklistRequest($campaign_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');

        $resourcePath = '/campaigns/{campaign_id}/send-checklist';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function updateRequest($campaign_id, $body): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/campaigns/{campaign_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);

        return $this->buildRequest('PATCH', $resourcePath, $queryParams, $body);
    }

    protected function updateFeedbackMessageRequest($campaign_id, $feedback_id, $body): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');
        $this->requireParam($feedback_id, 'feedback_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/campaigns/{campaign_id}/feedback/{feedback_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);
        $this->replacePathParam($resourcePath, 'feedback_id', $feedback_id);

        return $this->buildRequest('PATCH', $resourcePath, $queryParams, $body);
    }

    protected function createRequest($body): Request
    {
        $this->requireParam($body, 'body');

        $resourcePath = '/campaigns';
        $queryParams = [];

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function cancelSendRequest($campaign_id): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');

        $resourcePath = '/campaigns/{campaign_id}/actions/cancel-send';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams);
    }

    protected function createResendRequest($campaign_id): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');

        $resourcePath = '/campaigns/{campaign_id}/actions/create-resend';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams);
    }

    protected function pauseRequest($campaign_id): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');

        $resourcePath = '/campaigns/{campaign_id}/actions/pause';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams);
    }

    protected function replicateRequest($campaign_id): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');

        $resourcePath = '/campaigns/{campaign_id}/actions/replicate';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams);
    }

    protected function resumeRequest($campaign_id): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');

        $resourcePath = '/campaigns/{campaign_id}/actions/resume';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams);
    }

    protected function scheduleRequest($campaign_id, $body): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/campaigns/{campaign_id}/actions/schedule';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function sendRequest($request): Request
    {
        $this->requireParam($request, 'campaign_id');

        $resourcePath = '/campaigns/{campaign_id}/actions/send';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'campaign_id', $request);

        return $this->buildRequest('POST', $resourcePath, $queryParams);
    }

    protected function sendTestEmailRequest($campaign_id, $body): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/campaigns/{campaign_id}/actions/test';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function unscheduleRequest($campaign_id): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');

        $resourcePath = '/campaigns/{campaign_id}/actions/unschedule';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams);
    }

    protected function addFeedbackRequest($campaign_id, $body): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/campaigns/{campaign_id}/feedback';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function setContentRequest($campaign_id, $body): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/campaigns/{campaign_id}/content';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);

        return $this->buildRequest('PUT', $resourcePath, $queryParams, $body);
    }
}
