<?php

declare(strict_types=1);

/**
 * ConnectedSitesApi
 * PHP version 5.
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mailchimp Marketing API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.80
 * Contact: apihelp@mailchimp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MailchimpMarketing\Api;

use GuzzleHttp\Psr7\Request;

class ConnectedSitesApi extends AbstractApi
{
    public function remove($connected_site_id): void
    {
        $this->removeWithHttpInfo($connected_site_id);
    }

    public function removeWithHttpInfo($connected_site_id)
    {
        $request = $this->removeRequest($connected_site_id);

        return $this->sendRequest($request);
    }

    public function list($fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        return $this->listWithHttpInfo($fields, $exclude_fields, $count, $offset);
    }

    public function listWithHttpInfo($fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        $request = $this->listRequest($fields, $exclude_fields, $count, $offset);

        return $this->sendRequest($request);
    }

    public function get($connected_site_id, $fields = null, $exclude_fields = null)
    {
        return $this->getWithHttpInfo($connected_site_id, $fields, $exclude_fields);
    }

    public function getWithHttpInfo($connected_site_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getRequest($connected_site_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function create($body)
    {
        return $this->createWithHttpInfo($body);
    }

    public function createWithHttpInfo($body)
    {
        $request = $this->createRequest($body);

        return $this->sendRequest($request);
    }

    public function verifyScriptInstallation($connected_site_id): void
    {
        $this->verifyScriptInstallationWithHttpInfo($connected_site_id);
    }

    public function verifyScriptInstallationWithHttpInfo($connected_site_id)
    {
        $request = $this->verifyScriptInstallationRequest($connected_site_id);

        return $this->sendRequest($request);
    }

    protected function removeRequest($connected_site_id): Request
    {
        $this->requireParam($connected_site_id, 'connected_site_id');

        $resourcePath = '/connected-sites/{connected_site_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'connected_site_id', $connected_site_id);

        return $this->buildRequest('DELETE', $resourcePath, $queryParams);
    }

    protected function listRequest($fields = null, $exclude_fields = null, $count = '10', $offset = '0'): Request
    {
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ConnectedSitesApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/connected-sites';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getRequest($connected_site_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($connected_site_id, 'connected_site_id');

        $resourcePath = '/connected-sites/{connected_site_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'connected_site_id', $connected_site_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function createRequest($body): Request
    {
        $this->requireParam($body, 'body');

        $resourcePath = '/connected-sites';
        $queryParams = [];

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function verifyScriptInstallationRequest($connected_site_id): Request
    {
        $this->requireParam($connected_site_id, 'connected_site_id');

        $resourcePath = '/connected-sites/{connected_site_id}/actions/verify-script-installation';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'connected_site_id', $connected_site_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams);
    }
}
