<?php

declare(strict_types=1);

/**
 * CustomerJourneysApi
 * PHP version 5.
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mailchimp Marketing API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.80
 * Contact: apihelp@mailchimp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MailchimpMarketing\Api;

use GuzzleHttp\Psr7\Request;

class CustomerJourneysApi extends AbstractApi
{
    public function trigger($journey_id, $step_id, $body)
    {
        return $this->triggerWithHttpInfo($journey_id, $step_id, $body);
    }

    public function triggerWithHttpInfo($journey_id, $step_id, $body)
    {
        $request = $this->triggerRequest($journey_id, $step_id, $body);

        return $this->sendRequest($request);
    }

    protected function triggerRequest($journey_id, $step_id, $body): Request
    {
        $this->requireParam($journey_id, 'journey_id');
        $this->requireParam($step_id, 'step_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/customer-journeys/journeys/{journey_id}/steps/{step_id}/actions/trigger';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'journey_id', $journey_id);
        $this->replacePathParam($resourcePath, 'step_id', $step_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }
}
