<?php

declare(strict_types=1);

/**
 * EcommerceApi
 * PHP version 5.
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mailchimp Marketing API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.80
 * Contact: apihelp@mailchimp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MailchimpMarketing\Api;

use GuzzleHttp\Psr7\Request;

class EcommerceApi extends AbstractApi
{
    public function deleteStore($store_id)
    {
        return $this->deleteStoreWithHttpInfo($store_id);
    }

    public function deleteStoreWithHttpInfo($store_id)
    {
        $request = $this->deleteStoreRequest($store_id);

        return $this->sendRequest($request);
    }

    public function deleteStoreCart($store_id, $cart_id): void
    {
        $this->deleteStoreCartWithHttpInfo($store_id, $cart_id);
    }

    public function deleteStoreCartWithHttpInfo($store_id, $cart_id)
    {
        $request = $this->deleteStoreCartRequest($store_id, $cart_id);

        return $this->sendRequest($request);
    }

    public function deleteCartLineItem($store_id, $cart_id, $line_id): void
    {
        $this->deleteCartLineItemWithHttpInfo($store_id, $cart_id, $line_id);
    }

    public function deleteCartLineItemWithHttpInfo($store_id, $cart_id, $line_id)
    {
        $request = $this->deleteCartLineItemRequest($store_id, $cart_id, $line_id);

        return $this->sendRequest($request);
    }

    public function deleteStoreCustomer($store_id, $customer_id): void
    {
        $this->deleteStoreCustomerWithHttpInfo($store_id, $customer_id);
    }

    public function deleteStoreCustomerWithHttpInfo($store_id, $customer_id)
    {
        $request = $this->deleteStoreCustomerRequest($store_id, $customer_id);

        return $this->sendRequest($request);
    }

    public function deleteOrder($store_id, $order_id): void
    {
        $this->deleteOrderWithHttpInfo($store_id, $order_id);
    }

    public function deleteOrderWithHttpInfo($store_id, $order_id)
    {
        $request = $this->deleteOrderRequest($store_id, $order_id);

        return $this->sendRequest($request);
    }

    public function deleteOrderLineItem($store_id, $order_id, $line_id): void
    {
        $this->deleteOrderLineItemWithHttpInfo($store_id, $order_id, $line_id);
    }

    public function deleteOrderLineItemWithHttpInfo($store_id, $order_id, $line_id)
    {
        $request = $this->deleteOrderLineItemRequest($store_id, $order_id, $line_id);

        return $this->sendRequest($request);
    }

    public function deleteStoreProduct($store_id, $product_id): void
    {
        $this->deleteStoreProductWithHttpInfo($store_id, $product_id);
    }

    public function deleteStoreProductWithHttpInfo($store_id, $product_id)
    {
        $request = $this->deleteStoreProductRequest($store_id, $product_id);

        return $this->sendRequest($request);
    }

    public function deleteProductImage($store_id, $product_id, $image_id): void
    {
        $this->deleteProductImageWithHttpInfo($store_id, $product_id, $image_id);
    }

    public function deleteProductImageWithHttpInfo($store_id, $product_id, $image_id)
    {
        $request = $this->deleteProductImageRequest($store_id, $product_id, $image_id);

        return $this->sendRequest($request);
    }

    public function deleteProductVariant($store_id, $product_id, $variant_id): void
    {
        $this->deleteProductVariantWithHttpInfo($store_id, $product_id, $variant_id);
    }

    public function deleteProductVariantWithHttpInfo($store_id, $product_id, $variant_id)
    {
        $request = $this->deleteProductVariantRequest($store_id, $product_id, $variant_id);

        return $this->sendRequest($request);
    }

    public function deletePromoCode($store_id, $promo_rule_id, $promo_code_id): void
    {
        $this->deletePromoCodeWithHttpInfo($store_id, $promo_rule_id, $promo_code_id);
    }

    public function deletePromoCodeWithHttpInfo($store_id, $promo_rule_id, $promo_code_id)
    {
        $request = $this->deletePromoCodeRequest($store_id, $promo_rule_id, $promo_code_id);

        return $this->sendRequest($request);
    }

    public function deletePromoRule($store_id, $promo_rule_id): void
    {
        $this->deletePromoRuleWithHttpInfo($store_id, $promo_rule_id);
    }

    public function deletePromoRuleWithHttpInfo($store_id, $promo_rule_id)
    {
        $request = $this->deletePromoRuleRequest($store_id, $promo_rule_id);

        return $this->sendRequest($request);
    }

    public function orders($fields = null, $exclude_fields = null, $count = '10', $offset = '0', $campaign_id = null, $outreach_id = null, $customer_id = null, $has_outreach = null)
    {
        return $this->ordersWithHttpInfo($fields, $exclude_fields, $count, $offset, $campaign_id, $outreach_id, $customer_id, $has_outreach);
    }

    public function ordersWithHttpInfo($fields = null, $exclude_fields = null, $count = '10', $offset = '0', $campaign_id = null, $outreach_id = null, $customer_id = null, $has_outreach = null)
    {
        $request = $this->ordersRequest($fields, $exclude_fields, $count, $offset, $campaign_id, $outreach_id, $customer_id, $has_outreach);

        return $this->sendRequest($request);
    }

    public function stores($fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        return $this->storesWithHttpInfo($fields, $exclude_fields, $count, $offset);
    }

    public function storesWithHttpInfo($fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        $request = $this->storesRequest($fields, $exclude_fields, $count, $offset);

        return $this->sendRequest($request);
    }

    public function getStore($store_id, $fields = null, $exclude_fields = null)
    {
        return $this->getStoreWithHttpInfo($store_id, $fields, $exclude_fields);
    }

    public function getStoreWithHttpInfo($store_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getStoreRequest($store_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getStoreCarts($store_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        return $this->getStoreCartsWithHttpInfo($store_id, $fields, $exclude_fields, $count, $offset);
    }

    public function getStoreCartsWithHttpInfo($store_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        $request = $this->getStoreCartsRequest($store_id, $fields, $exclude_fields, $count, $offset);

        return $this->sendRequest($request);
    }

    public function getStoreCart($store_id, $cart_id, $fields = null, $exclude_fields = null)
    {
        return $this->getStoreCartWithHttpInfo($store_id, $cart_id, $fields, $exclude_fields);
    }

    public function getStoreCartWithHttpInfo($store_id, $cart_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getStoreCartRequest($store_id, $cart_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getAllCartLineItems($store_id, $cart_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        return $this->getAllCartLineItemsWithHttpInfo($store_id, $cart_id, $fields, $exclude_fields, $count, $offset);
    }

    public function getAllCartLineItemsWithHttpInfo($store_id, $cart_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        $request = $this->getAllCartLineItemsRequest($store_id, $cart_id, $fields, $exclude_fields, $count, $offset);

        return $this->sendRequest($request);
    }

    public function getCartLineItem($store_id, $cart_id, $line_id, $fields = null, $exclude_fields = null)
    {
        return $this->getCartLineItemWithHttpInfo($store_id, $cart_id, $line_id, $fields, $exclude_fields);
    }

    public function getCartLineItemWithHttpInfo($store_id, $cart_id, $line_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getCartLineItemRequest($store_id, $cart_id, $line_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getAllStoreCustomers($store_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $email_address = null)
    {
        return $this->getAllStoreCustomersWithHttpInfo($store_id, $fields, $exclude_fields, $count, $offset, $email_address);
    }

    public function getAllStoreCustomersWithHttpInfo($store_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $email_address = null)
    {
        $request = $this->getAllStoreCustomersRequest($store_id, $fields, $exclude_fields, $count, $offset, $email_address);

        return $this->sendRequest($request);
    }

    public function getStoreCustomer($store_id, $customer_id, $fields = null, $exclude_fields = null)
    {
        return $this->getStoreCustomerWithHttpInfo($store_id, $customer_id, $fields, $exclude_fields);
    }

    public function getStoreCustomerWithHttpInfo($store_id, $customer_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getStoreCustomerRequest($store_id, $customer_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getStoreOrders($store_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $customer_id = null, $has_outreach = null, $campaign_id = null, $outreach_id = null)
    {
        return $this->getStoreOrdersWithHttpInfo($store_id, $fields, $exclude_fields, $count, $offset, $customer_id, $has_outreach, $campaign_id, $outreach_id);
    }

    public function getStoreOrdersWithHttpInfo($store_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $customer_id = null, $has_outreach = null, $campaign_id = null, $outreach_id = null)
    {
        $request = $this->getStoreOrdersRequest($store_id, $fields, $exclude_fields, $count, $offset, $customer_id, $has_outreach, $campaign_id, $outreach_id);

        return $this->sendRequest($request);
    }

    public function getOrder($store_id, $order_id, $fields = null, $exclude_fields = null)
    {
        return $this->getOrderWithHttpInfo($store_id, $order_id, $fields, $exclude_fields);
    }

    public function getOrderWithHttpInfo($store_id, $order_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getOrderRequest($store_id, $order_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getAllOrderLineItems($store_id, $order_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        return $this->getAllOrderLineItemsWithHttpInfo($store_id, $order_id, $fields, $exclude_fields, $count, $offset);
    }

    public function getAllOrderLineItemsWithHttpInfo($store_id, $order_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        $request = $this->getAllOrderLineItemsRequest($store_id, $order_id, $fields, $exclude_fields, $count, $offset);

        return $this->sendRequest($request);
    }

    public function getOrderLineItem($store_id, $order_id, $line_id, $fields = null, $exclude_fields = null)
    {
        return $this->getOrderLineItemWithHttpInfo($store_id, $order_id, $line_id, $fields, $exclude_fields);
    }

    public function getOrderLineItemWithHttpInfo($store_id, $order_id, $line_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getOrderLineItemRequest($store_id, $order_id, $line_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getAllStoreProducts($store_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        return $this->getAllStoreProductsWithHttpInfo($store_id, $fields, $exclude_fields, $count, $offset);
    }

    public function getAllStoreProductsWithHttpInfo($store_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        $request = $this->getAllStoreProductsRequest($store_id, $fields, $exclude_fields, $count, $offset);

        return $this->sendRequest($request);
    }

    public function getStoreProduct($store_id, $product_id, $fields = null, $exclude_fields = null)
    {
        return $this->getStoreProductWithHttpInfo($store_id, $product_id, $fields, $exclude_fields);
    }

    public function getStoreProductWithHttpInfo($store_id, $product_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getStoreProductRequest($store_id, $product_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getProductImages($store_id, $product_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        return $this->getProductImagesWithHttpInfo($store_id, $product_id, $fields, $exclude_fields, $count, $offset);
    }

    public function getProductImagesWithHttpInfo($store_id, $product_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        $request = $this->getProductImagesRequest($store_id, $product_id, $fields, $exclude_fields, $count, $offset);

        return $this->sendRequest($request);
    }

    public function getProductImage($store_id, $product_id, $image_id, $fields = null, $exclude_fields = null)
    {
        return $this->getProductImageWithHttpInfo($store_id, $product_id, $image_id, $fields, $exclude_fields);
    }

    public function getProductImageWithHttpInfo($store_id, $product_id, $image_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getProductImageRequest($store_id, $product_id, $image_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getProductVariants($store_id, $product_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        return $this->getProductVariantsWithHttpInfo($store_id, $product_id, $fields, $exclude_fields, $count, $offset);
    }

    public function getProductVariantsWithHttpInfo($store_id, $product_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        $request = $this->getProductVariantsRequest($store_id, $product_id, $fields, $exclude_fields, $count, $offset);

        return $this->sendRequest($request);
    }

    public function getProductVariant($store_id, $product_id, $variant_id, $fields = null, $exclude_fields = null)
    {
        return $this->getProductVariantWithHttpInfo($store_id, $product_id, $variant_id, $fields, $exclude_fields);
    }

    public function getProductVariantWithHttpInfo($store_id, $product_id, $variant_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getProductVariantRequest($store_id, $product_id, $variant_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getPromoCodes($promo_rule_id, $store_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        return $this->getPromoCodesWithHttpInfo($promo_rule_id, $store_id, $fields, $exclude_fields, $count, $offset);
    }

    public function getPromoCodesWithHttpInfo($promo_rule_id, $store_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        $request = $this->getPromoCodesRequest($promo_rule_id, $store_id, $fields, $exclude_fields, $count, $offset);

        return $this->sendRequest($request);
    }

    public function getPromoCode($store_id, $promo_rule_id, $promo_code_id, $fields = null, $exclude_fields = null)
    {
        return $this->getPromoCodeWithHttpInfo($store_id, $promo_rule_id, $promo_code_id, $fields, $exclude_fields);
    }

    public function getPromoCodeWithHttpInfo($store_id, $promo_rule_id, $promo_code_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getPromoCodeRequest($store_id, $promo_rule_id, $promo_code_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function listPromoRules($store_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        return $this->listPromoRulesWithHttpInfo($store_id, $fields, $exclude_fields, $count, $offset);
    }

    public function listPromoRulesWithHttpInfo($store_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        $request = $this->listPromoRulesRequest($store_id, $fields, $exclude_fields, $count, $offset);

        return $this->sendRequest($request);
    }

    public function getPromoRule($store_id, $promo_rule_id, $fields = null, $exclude_fields = null)
    {
        return $this->getPromoRuleWithHttpInfo($store_id, $promo_rule_id, $fields, $exclude_fields);
    }

    public function getPromoRuleWithHttpInfo($store_id, $promo_rule_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getPromoRuleRequest($store_id, $promo_rule_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function updateStore($store_id, $body)
    {
        return $this->updateStoreWithHttpInfo($store_id, $body);
    }

    public function updateStoreWithHttpInfo($store_id, $body)
    {
        $request = $this->updateStoreRequest($store_id, $body);

        return $this->sendRequest($request);
    }

    public function updateStoreCart($store_id, $cart_id, $body)
    {
        return $this->updateStoreCartWithHttpInfo($store_id, $cart_id, $body);
    }

    public function updateStoreCartWithHttpInfo($store_id, $cart_id, $body)
    {
        $request = $this->updateStoreCartRequest($store_id, $cart_id, $body);

        return $this->sendRequest($request);
    }

    public function updateCartLineItem($store_id, $cart_id, $line_id, $body)
    {
        return $this->updateCartLineItemWithHttpInfo($store_id, $cart_id, $line_id, $body);
    }

    public function updateCartLineItemWithHttpInfo($store_id, $cart_id, $line_id, $body)
    {
        $request = $this->updateCartLineItemRequest($store_id, $cart_id, $line_id, $body);

        return $this->sendRequest($request);
    }

    public function updateStoreCustomer($store_id, $customer_id, $body)
    {
        return $this->updateStoreCustomerWithHttpInfo($store_id, $customer_id, $body);
    }

    public function updateStoreCustomerWithHttpInfo($store_id, $customer_id, $body)
    {
        $request = $this->updateStoreCustomerRequest($store_id, $customer_id, $body);

        return $this->sendRequest($request);
    }

    public function updateOrder($store_id, $order_id, $body)
    {
        return $this->updateOrderWithHttpInfo($store_id, $order_id, $body);
    }

    public function updateOrderWithHttpInfo($store_id, $order_id, $body)
    {
        $request = $this->updateOrderRequest($store_id, $order_id, $body);

        return $this->sendRequest($request);
    }

    public function updateOrderLineItem($store_id, $order_id, $line_id, $body)
    {
        return $this->updateOrderLineItemWithHttpInfo($store_id, $order_id, $line_id, $body);
    }

    public function updateOrderLineItemWithHttpInfo($store_id, $order_id, $line_id, $body)
    {
        $request = $this->updateOrderLineItemRequest($store_id, $order_id, $line_id, $body);

        return $this->sendRequest($request);
    }

    public function updateStoreProduct($store_id, $product_id, $body)
    {
        return $this->updateStoreProductWithHttpInfo($store_id, $product_id, $body);
    }

    public function updateStoreProductWithHttpInfo($store_id, $product_id, $body)
    {
        $request = $this->updateStoreProductRequest($store_id, $product_id, $body);

        return $this->sendRequest($request);
    }

    public function updateProductImage($store_id, $product_id, $image_id, $body)
    {
        return $this->updateProductImageWithHttpInfo($store_id, $product_id, $image_id, $body);
    }

    public function updateProductImageWithHttpInfo($store_id, $product_id, $image_id, $body)
    {
        $request = $this->updateProductImageRequest($store_id, $product_id, $image_id, $body);

        return $this->sendRequest($request);
    }

    public function updateProductVariant($store_id, $product_id, $variant_id, $body)
    {
        return $this->updateProductVariantWithHttpInfo($store_id, $product_id, $variant_id, $body);
    }

    public function updateProductVariantWithHttpInfo($store_id, $product_id, $variant_id, $body)
    {
        $request = $this->updateProductVariantRequest($store_id, $product_id, $variant_id, $body);

        return $this->sendRequest($request);
    }

    public function updatePromoCode($store_id, $promo_rule_id, $promo_code_id, $body)
    {
        return $this->updatePromoCodeWithHttpInfo($store_id, $promo_rule_id, $promo_code_id, $body);
    }

    public function updatePromoCodeWithHttpInfo($store_id, $promo_rule_id, $promo_code_id, $body)
    {
        $request = $this->updatePromoCodeRequest($store_id, $promo_rule_id, $promo_code_id, $body);

        return $this->sendRequest($request);
    }

    public function updatePromoRule($store_id, $promo_rule_id, $body)
    {
        return $this->updatePromoRuleWithHttpInfo($store_id, $promo_rule_id, $body);
    }

    public function updatePromoRuleWithHttpInfo($store_id, $promo_rule_id, $body)
    {
        $request = $this->updatePromoRuleRequest($store_id, $promo_rule_id, $body);

        return $this->sendRequest($request);
    }

    public function addStore($body)
    {
        return $this->addStoreWithHttpInfo($body);
    }

    public function addStoreWithHttpInfo($body)
    {
        $request = $this->addStoreRequest($body);

        return $this->sendRequest($request);
    }

    public function addStoreCart($store_id, $body)
    {
        return $this->addStoreCartWithHttpInfo($store_id, $body);
    }

    public function addStoreCartWithHttpInfo($store_id, $body)
    {
        $request = $this->addStoreCartRequest($store_id, $body);

        return $this->sendRequest($request);
    }

    public function addCartLineItem($store_id, $cart_id, $body)
    {
        return $this->addCartLineItemWithHttpInfo($store_id, $cart_id, $body);
    }

    public function addCartLineItemWithHttpInfo($store_id, $cart_id, $body)
    {
        $request = $this->addCartLineItemRequest($store_id, $cart_id, $body);

        return $this->sendRequest($request);
    }

    public function addStoreCustomer($store_id, $body)
    {
        return $this->addStoreCustomerWithHttpInfo($store_id, $body);
    }

    public function addStoreCustomerWithHttpInfo($store_id, $body)
    {
        $request = $this->addStoreCustomerRequest($store_id, $body);

        return $this->sendRequest($request);
    }

    public function addStoreOrder($store_id, $body)
    {
        return $this->addStoreOrderWithHttpInfo($store_id, $body);
    }

    public function addStoreOrderWithHttpInfo($store_id, $body)
    {
        $request = $this->addStoreOrderRequest($store_id, $body);

        return $this->sendRequest($request);
    }

    public function addOrderLineItem($store_id, $order_id, $body)
    {
        return $this->addOrderLineItemWithHttpInfo($store_id, $order_id, $body);
    }

    public function addOrderLineItemWithHttpInfo($store_id, $order_id, $body)
    {
        $request = $this->addOrderLineItemRequest($store_id, $order_id, $body);

        return $this->sendRequest($request);
    }

    public function addStoreProduct($store_id, $body)
    {
        return $this->addStoreProductWithHttpInfo($store_id, $body);
    }

    public function addStoreProductWithHttpInfo($store_id, $body)
    {
        $request = $this->addStoreProductRequest($store_id, $body);

        return $this->sendRequest($request);
    }

    public function addProductImage($store_id, $product_id, $body)
    {
        return $this->addProductImageWithHttpInfo($store_id, $product_id, $body);
    }

    public function addProductImageWithHttpInfo($store_id, $product_id, $body)
    {
        $request = $this->addProductImageRequest($store_id, $product_id, $body);

        return $this->sendRequest($request);
    }

    public function addProductVariants($store_id, $product_id, $body)
    {
        return $this->addProductVariantsWithHttpInfo($store_id, $product_id, $body);
    }

    public function addProductVariantsWithHttpInfo($store_id, $product_id, $body)
    {
        $request = $this->addProductVariantsRequest($store_id, $product_id, $body);

        return $this->sendRequest($request);
    }

    public function addPromoCode($store_id, $promo_rule_id, $body)
    {
        return $this->addPromoCodeWithHttpInfo($store_id, $promo_rule_id, $body);
    }

    public function addPromoCodeWithHttpInfo($store_id, $promo_rule_id, $body)
    {
        $request = $this->addPromoCodeRequest($store_id, $promo_rule_id, $body);

        return $this->sendRequest($request);
    }

    public function addPromoRules($store_id, $body)
    {
        return $this->addPromoRulesWithHttpInfo($store_id, $body);
    }

    public function addPromoRulesWithHttpInfo($store_id, $body)
    {
        $request = $this->addPromoRulesRequest($store_id, $body);

        return $this->sendRequest($request);
    }

    public function setStoreCustomer($store_id, $customer_id, $body)
    {
        return $this->setStoreCustomerWithHttpInfo($store_id, $customer_id, $body);
    }

    public function setStoreCustomerWithHttpInfo($store_id, $customer_id, $body)
    {
        $request = $this->setStoreCustomerRequest($store_id, $customer_id, $body);

        return $this->sendRequest($request);
    }

    public function addProductVariant($store_id, $product_id, $variant_id, $body)
    {
        return $this->addProductVariantWithHttpInfo($store_id, $product_id, $variant_id, $body);
    }

    public function addProductVariantWithHttpInfo($store_id, $product_id, $variant_id, $body)
    {
        $request = $this->addProductVariantRequest($store_id, $product_id, $variant_id, $body);

        return $this->sendRequest($request);
    }

    protected function deleteStoreRequest($store_id): Request
    {
        $this->requireParam($store_id, 'store_id');

        $resourcePath = '/ecommerce/stores/{store_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);

        return $this->buildRequest('DELETE', $resourcePath, $queryParams);
    }

    protected function deleteStoreCartRequest($store_id, $cart_id): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($cart_id, 'cart_id');

        $resourcePath = '/ecommerce/stores/{store_id}/carts/{cart_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'cart_id', $cart_id);

        return $this->buildRequest('DELETE', $resourcePath, $queryParams);
    }

    protected function deleteCartLineItemRequest($store_id, $cart_id, $line_id): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($cart_id, 'cart_id');
        $this->requireParam($line_id, 'line_id');

        $resourcePath = '/ecommerce/stores/{store_id}/carts/{cart_id}/lines/{line_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'cart_id', $cart_id);
        $this->replacePathParam($resourcePath, 'line_id', $line_id);

        return $this->buildRequest('DELETE', $resourcePath, $queryParams);
    }

    protected function deleteStoreCustomerRequest($store_id, $customer_id): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($customer_id, 'customer_id');

        $resourcePath = '/ecommerce/stores/{store_id}/customers/{customer_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'customer_id', $customer_id);

        return $this->buildRequest('DELETE', $resourcePath, $queryParams);
    }

    protected function deleteOrderRequest($store_id, $order_id): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($order_id, 'order_id');

        $resourcePath = '/ecommerce/stores/{store_id}/orders/{order_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'order_id', $order_id);

        return $this->buildRequest('DELETE', $resourcePath, $queryParams);
    }

    protected function deleteOrderLineItemRequest($store_id, $order_id, $line_id): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($order_id, 'order_id');
        $this->requireParam($line_id, 'line_id');

        $resourcePath = '/ecommerce/stores/{store_id}/orders/{order_id}/lines/{line_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'order_id', $order_id);
        $this->replacePathParam($resourcePath, 'line_id', $line_id);

        return $this->buildRequest('DELETE', $resourcePath, $queryParams);
    }

    protected function deleteStoreProductRequest($store_id, $product_id): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($product_id, 'product_id');

        $resourcePath = '/ecommerce/stores/{store_id}/products/{product_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'product_id', $product_id);

        return $this->buildRequest('DELETE', $resourcePath, $queryParams);
    }

    protected function deleteProductImageRequest($store_id, $product_id, $image_id): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($product_id, 'product_id');
        $this->requireParam($image_id, 'image_id');

        $resourcePath = '/ecommerce/stores/{store_id}/products/{product_id}/images/{image_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'product_id', $product_id);
        $this->replacePathParam($resourcePath, 'image_id', $image_id);

        return $this->buildRequest('DELETE', $resourcePath, $queryParams);
    }

    protected function deleteProductVariantRequest($store_id, $product_id, $variant_id): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($product_id, 'product_id');
        $this->requireParam($variant_id, 'variant_id');

        $resourcePath = '/ecommerce/stores/{store_id}/products/{product_id}/variants/{variant_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'product_id', $product_id);
        $this->replacePathParam($resourcePath, 'variant_id', $variant_id);

        return $this->buildRequest('DELETE', $resourcePath, $queryParams);
    }

    protected function deletePromoCodeRequest($store_id, $promo_rule_id, $promo_code_id): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($promo_rule_id, 'promo_rule_id');
        $this->requireParam($promo_code_id, 'promo_code_id');

        $resourcePath = '/ecommerce/stores/{store_id}/promo-rules/{promo_rule_id}/promo-codes/{promo_code_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'promo_rule_id', $promo_rule_id);
        $this->replacePathParam($resourcePath, 'promo_code_id', $promo_code_id);

        return $this->buildRequest('DELETE', $resourcePath, $queryParams);
    }

    protected function deletePromoRuleRequest($store_id, $promo_rule_id): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($promo_rule_id, 'promo_rule_id');

        $resourcePath = '/ecommerce/stores/{store_id}/promo-rules/{promo_rule_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'promo_rule_id', $promo_rule_id);

        return $this->buildRequest('DELETE', $resourcePath, $queryParams);
    }

    protected function ordersRequest($fields = null, $exclude_fields = null, $count = '10', $offset = '0', $campaign_id = null, $outreach_id = null, $customer_id = null, $has_outreach = null): Request
    {
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling EcommerceApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/ecommerce/orders';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);
        $this->addQueryParam($queryParams, 'campaign_id', $campaign_id);
        $this->addQueryParam($queryParams, 'outreach_id', $outreach_id);
        $this->addQueryParam($queryParams, 'customer_id', $customer_id);
        $this->addQueryParam($queryParams, 'has_outreach', $has_outreach);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function storesRequest($fields = null, $exclude_fields = null, $count = '10', $offset = '0'): Request
    {
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling EcommerceApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/ecommerce/stores';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getStoreRequest($store_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($store_id, 'store_id');

        $resourcePath = '/ecommerce/stores/{store_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'store_id', $store_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getStoreCartsRequest($store_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0'): Request
    {
        $this->requireParam($store_id, 'store_id');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling EcommerceApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/ecommerce/stores/{store_id}/carts';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);

        $this->replacePathParam($resourcePath, 'store_id', $store_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getStoreCartRequest($store_id, $cart_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($cart_id, 'cart_id');

        $resourcePath = '/ecommerce/stores/{store_id}/carts/{cart_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'cart_id', $cart_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getAllCartLineItemsRequest($store_id, $cart_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0'): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($cart_id, 'cart_id');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling EcommerceApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/ecommerce/stores/{store_id}/carts/{cart_id}/lines';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'cart_id', $cart_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getCartLineItemRequest($store_id, $cart_id, $line_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($cart_id, 'cart_id');
        $this->requireParam($line_id, 'line_id');

        $resourcePath = '/ecommerce/stores/{store_id}/carts/{cart_id}/lines/{line_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'cart_id', $cart_id);
        $this->replacePathParam($resourcePath, 'line_id', $line_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getAllStoreCustomersRequest($store_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $email_address = null): Request
    {
        $this->requireParam($store_id, 'store_id');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling EcommerceApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/ecommerce/stores/{store_id}/customers';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);
        $this->addQueryParam($queryParams, 'email_address', $email_address);

        $this->replacePathParam($resourcePath, 'store_id', $store_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getStoreCustomerRequest($store_id, $customer_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($customer_id, 'customer_id');

        $resourcePath = '/ecommerce/stores/{store_id}/customers/{customer_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'customer_id', $customer_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getStoreOrdersRequest($store_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $customer_id = null, $has_outreach = null, $campaign_id = null, $outreach_id = null): Request
    {
        $this->requireParam($store_id, 'store_id');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling EcommerceApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/ecommerce/stores/{store_id}/orders';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);
        $this->addQueryParam($queryParams, 'customer_id', $customer_id);
        $this->addQueryParam($queryParams, 'has_outreach', $has_outreach);
        $this->addQueryParam($queryParams, 'campaign_id', $campaign_id);
        $this->addQueryParam($queryParams, 'outreach_id', $outreach_id);

        $this->replacePathParam($resourcePath, 'store_id', $store_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getOrderRequest($store_id, $order_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($order_id, 'order_id');

        $resourcePath = '/ecommerce/stores/{store_id}/orders/{order_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'order_id', $order_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getAllOrderLineItemsRequest($store_id, $order_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0'): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($order_id, 'order_id');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling EcommerceApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/ecommerce/stores/{store_id}/orders/{order_id}/lines';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'order_id', $order_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getOrderLineItemRequest($store_id, $order_id, $line_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($order_id, 'order_id');
        $this->requireParam($line_id, 'line_id');

        $resourcePath = '/ecommerce/stores/{store_id}/orders/{order_id}/lines/{line_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'order_id', $order_id);
        $this->replacePathParam($resourcePath, 'line_id', $line_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getAllStoreProductsRequest($store_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0'): Request
    {
        $this->requireParam($store_id, 'store_id');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling EcommerceApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/ecommerce/stores/{store_id}/products';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);

        $this->replacePathParam($resourcePath, 'store_id', $store_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getStoreProductRequest($store_id, $product_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($product_id, 'product_id');

        $resourcePath = '/ecommerce/stores/{store_id}/products/{product_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'product_id', $product_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getProductImagesRequest($store_id, $product_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0'): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($product_id, 'product_id');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling EcommerceApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/ecommerce/stores/{store_id}/products/{product_id}/images';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'product_id', $product_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getProductImageRequest($store_id, $product_id, $image_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($product_id, 'product_id');
        $this->requireParam($image_id, 'image_id');

        $resourcePath = '/ecommerce/stores/{store_id}/products/{product_id}/images/{image_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'product_id', $product_id);
        $this->replacePathParam($resourcePath, 'image_id', $image_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getProductVariantsRequest($store_id, $product_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0'): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($product_id, 'product_id');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling EcommerceApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/ecommerce/stores/{store_id}/products/{product_id}/variants';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'product_id', $product_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getProductVariantRequest($store_id, $product_id, $variant_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($product_id, 'product_id');
        $this->requireParam($variant_id, 'variant_id');

        $resourcePath = '/ecommerce/stores/{store_id}/products/{product_id}/variants/{variant_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'product_id', $product_id);
        $this->replacePathParam($resourcePath, 'variant_id', $variant_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getPromoCodesRequest($promo_rule_id, $store_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0'): Request
    {
        $this->requireParam($promo_rule_id, 'promo_rule_id');
        $this->requireParam($store_id, 'store_id');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling EcommerceApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/ecommerce/stores/{store_id}/promo-rules/{promo_rule_id}/promo-codes';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);

        $this->replacePathParam($resourcePath, 'promo_rule_id', $promo_rule_id);
        $this->replacePathParam($resourcePath, 'store_id', $store_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getPromoCodeRequest($store_id, $promo_rule_id, $promo_code_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($promo_rule_id, 'promo_rule_id');
        $this->requireParam($promo_code_id, 'promo_code_id');

        $resourcePath = '/ecommerce/stores/{store_id}/promo-rules/{promo_rule_id}/promo-codes/{promo_code_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'promo_rule_id', $promo_rule_id);
        $this->replacePathParam($resourcePath, 'promo_code_id', $promo_code_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function listPromoRulesRequest($store_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0'): Request
    {
        $this->requireParam($store_id, 'store_id');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling EcommerceApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/ecommerce/stores/{store_id}/promo-rules';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);

        $this->replacePathParam($resourcePath, 'store_id', $store_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getPromoRuleRequest($store_id, $promo_rule_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($promo_rule_id, 'promo_rule_id');

        $resourcePath = '/ecommerce/stores/{store_id}/promo-rules/{promo_rule_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'promo_rule_id', $promo_rule_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function updateStoreRequest($store_id, $body): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/ecommerce/stores/{store_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);

        return $this->buildRequest('PATCH', $resourcePath, $queryParams, $body);
    }

    protected function updateStoreCartRequest($store_id, $cart_id, $body): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($cart_id, 'cart_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/ecommerce/stores/{store_id}/carts/{cart_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'cart_id', $cart_id);

        return $this->buildRequest('PATCH', $resourcePath, $queryParams, $body);
    }

    protected function updateCartLineItemRequest($store_id, $cart_id, $line_id, $body): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($cart_id, 'cart_id');
        $this->requireParam($line_id, 'line_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/ecommerce/stores/{store_id}/carts/{cart_id}/lines/{line_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'cart_id', $cart_id);
        $this->replacePathParam($resourcePath, 'line_id', $line_id);

        return $this->buildRequest('PATCH', $resourcePath, $queryParams, $body);
    }

    protected function updateStoreCustomerRequest($store_id, $customer_id, $body): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($customer_id, 'customer_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/ecommerce/stores/{store_id}/customers/{customer_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'customer_id', $customer_id);

        return $this->buildRequest('PATCH', $resourcePath, $queryParams, $body);
    }

    protected function updateOrderRequest($store_id, $order_id, $body): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($order_id, 'order_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/ecommerce/stores/{store_id}/orders/{order_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'order_id', $order_id);

        return $this->buildRequest('PATCH', $resourcePath, $queryParams, $body);
    }

    protected function updateOrderLineItemRequest($store_id, $order_id, $line_id, $body): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($order_id, 'order_id');
        $this->requireParam($line_id, 'line_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/ecommerce/stores/{store_id}/orders/{order_id}/lines/{line_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'order_id', $order_id);
        $this->replacePathParam($resourcePath, 'line_id', $line_id);

        return $this->buildRequest('PATCH', $resourcePath, $queryParams, $body);
    }

    protected function updateStoreProductRequest($store_id, $product_id, $body): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($product_id, 'product_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/ecommerce/stores/{store_id}/products/{product_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'product_id', $product_id);

        return $this->buildRequest('PATCH', $resourcePath, $queryParams, $body);
    }

    protected function updateProductImageRequest($store_id, $product_id, $image_id, $body): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($product_id, 'product_id');
        $this->requireParam($image_id, 'image_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/ecommerce/stores/{store_id}/products/{product_id}/images/{image_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'product_id', $product_id);
        $this->replacePathParam($resourcePath, 'image_id', $image_id);

        return $this->buildRequest('PATCH', $resourcePath, $queryParams, $body);
    }

    protected function updateProductVariantRequest($store_id, $product_id, $variant_id, $body): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($product_id, 'product_id');
        $this->requireParam($variant_id, 'variant_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/ecommerce/stores/{store_id}/products/{product_id}/variants/{variant_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'product_id', $product_id);
        $this->replacePathParam($resourcePath, 'variant_id', $variant_id);

        return $this->buildRequest('PATCH', $resourcePath, $queryParams, $body);
    }

    protected function updatePromoCodeRequest($store_id, $promo_rule_id, $promo_code_id, $body): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($promo_rule_id, 'promo_rule_id');
        $this->requireParam($promo_code_id, 'promo_code_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/ecommerce/stores/{store_id}/promo-rules/{promo_rule_id}/promo-codes/{promo_code_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'promo_rule_id', $promo_rule_id);
        $this->replacePathParam($resourcePath, 'promo_code_id', $promo_code_id);

        return $this->buildRequest('PATCH', $resourcePath, $queryParams, $body);
    }

    protected function updatePromoRuleRequest($store_id, $promo_rule_id, $body): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($promo_rule_id, 'promo_rule_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/ecommerce/stores/{store_id}/promo-rules/{promo_rule_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'promo_rule_id', $promo_rule_id);

        return $this->buildRequest('PATCH', $resourcePath, $queryParams, $body);
    }

    protected function addStoreRequest($body): Request
    {
        $this->requireParam($body, 'body');

        $resourcePath = '/ecommerce/stores';
        $queryParams = [];

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function addStoreCartRequest($store_id, $body): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/ecommerce/stores/{store_id}/carts';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function addCartLineItemRequest($store_id, $cart_id, $body): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($cart_id, 'cart_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/ecommerce/stores/{store_id}/carts/{cart_id}/lines';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'cart_id', $cart_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function addStoreCustomerRequest($store_id, $body): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/ecommerce/stores/{store_id}/customers';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function addStoreOrderRequest($store_id, $body): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/ecommerce/stores/{store_id}/orders';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function addOrderLineItemRequest($store_id, $order_id, $body): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($order_id, 'order_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/ecommerce/stores/{store_id}/orders/{order_id}/lines';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'order_id', $order_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function addStoreProductRequest($store_id, $body): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/ecommerce/stores/{store_id}/products';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function addProductImageRequest($store_id, $product_id, $body): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($product_id, 'product_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/ecommerce/stores/{store_id}/products/{product_id}/images';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'product_id', $product_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function addProductVariantsRequest($store_id, $product_id, $body): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($product_id, 'product_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/ecommerce/stores/{store_id}/products/{product_id}/variants';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'product_id', $product_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function addPromoCodeRequest($store_id, $promo_rule_id, $body): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($promo_rule_id, 'promo_rule_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/ecommerce/stores/{store_id}/promo-rules/{promo_rule_id}/promo-codes';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'promo_rule_id', $promo_rule_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function addPromoRulesRequest($store_id, $body): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/ecommerce/stores/{store_id}/promo-rules';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function setStoreCustomerRequest($store_id, $customer_id, $body): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($customer_id, 'customer_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/ecommerce/stores/{store_id}/customers/{customer_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'customer_id', $customer_id);

        return $this->buildRequest('PUT', $resourcePath, $queryParams, $body);
    }

    protected function addProductVariantRequest($store_id, $product_id, $variant_id, $body): Request
    {
        $this->requireParam($store_id, 'store_id');
        $this->requireParam($product_id, 'product_id');
        $this->requireParam($variant_id, 'variant_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/ecommerce/stores/{store_id}/products/{product_id}/variants/{variant_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'store_id', $store_id);
        $this->replacePathParam($resourcePath, 'product_id', $product_id);
        $this->replacePathParam($resourcePath, 'variant_id', $variant_id);

        return $this->buildRequest('PUT', $resourcePath, $queryParams, $body);
    }
}
