<?php

declare(strict_types=1);

/**
 * FacebookAdsApi
 * PHP version 5.
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mailchimp Marketing API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.80
 * Contact: apihelp@mailchimp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MailchimpMarketing\Api;

use GuzzleHttp\Psr7\Request;

class FacebookAdsApi extends AbstractApi
{
    public function list($fields = null, $exclude_fields = null, $count = '10', $offset = '0', $sort_field = null, $sort_dir = null)
    {
        return $this->listWithHttpInfo($fields, $exclude_fields, $count, $offset, $sort_field, $sort_dir);
    }

    public function listWithHttpInfo($fields = null, $exclude_fields = null, $count = '10', $offset = '0', $sort_field = null, $sort_dir = null)
    {
        $request = $this->listRequest($fields, $exclude_fields, $count, $offset, $sort_field, $sort_dir);

        return $this->sendRequest($request);
    }

    public function getAd($outreach_id, $fields = null, $exclude_fields = null)
    {
        return $this->getAdWithHttpInfo($outreach_id, $fields, $exclude_fields);
    }

    public function getAdWithHttpInfo($outreach_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getAdRequest($outreach_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    protected function listRequest($fields = null, $exclude_fields = null, $count = '10', $offset = '0', $sort_field = null, $sort_dir = null): Request
    {
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling FacebookAdsApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/facebook-ads';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);
        $this->addQueryParam($queryParams, 'sort_field', $sort_field);
        $this->addQueryParam($queryParams, 'sort_dir', $sort_dir);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getAdRequest($outreach_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($outreach_id, 'outreach_id');

        $resourcePath = '/facebook-ads/{outreach_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'outreach_id', $outreach_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }
}
