<?php

declare(strict_types=1);

/**
 * ListsApi
 * PHP version 5.
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mailchimp Marketing API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.80
 * Contact: apihelp@mailchimp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MailchimpMarketing\Api;

use GuzzleHttp\Psr7\Request;

class ListsApi extends AbstractApi
{
    public function deleteList($list_id): void
    {
        $this->deleteListWithHttpInfo($list_id);
    }

    public function deleteListWithHttpInfo($list_id)
    {
        $request = $this->deleteListRequest($list_id);

        return $this->sendRequest($request);
    }

    public function deleteInterestCategory($list_id, $interest_category_id): void
    {
        $this->deleteInterestCategoryWithHttpInfo($list_id, $interest_category_id);
    }

    public function deleteInterestCategoryWithHttpInfo($list_id, $interest_category_id)
    {
        $request = $this->deleteInterestCategoryRequest($list_id, $interest_category_id);

        return $this->sendRequest($request);
    }

    public function deleteInterestCategoryInterest($list_id, $interest_category_id, $interest_id): void
    {
        $this->deleteInterestCategoryInterestWithHttpInfo($list_id, $interest_category_id, $interest_id);
    }

    public function deleteInterestCategoryInterestWithHttpInfo($list_id, $interest_category_id, $interest_id)
    {
        $request = $this->deleteInterestCategoryInterestRequest($list_id, $interest_category_id, $interest_id);

        return $this->sendRequest($request);
    }

    public function deleteListMember($list_id, $subscriber_hash): void
    {
        $this->deleteListMemberWithHttpInfo($list_id, $subscriber_hash);
    }

    public function deleteListMemberWithHttpInfo($list_id, $subscriber_hash)
    {
        $request = $this->deleteListMemberRequest($list_id, $subscriber_hash);

        return $this->sendRequest($request);
    }

    public function deleteListMemberNote($list_id, $subscriber_hash, $note_id): void
    {
        $this->deleteListMemberNoteWithHttpInfo($list_id, $subscriber_hash, $note_id);
    }

    public function deleteListMemberNoteWithHttpInfo($list_id, $subscriber_hash, $note_id)
    {
        $request = $this->deleteListMemberNoteRequest($list_id, $subscriber_hash, $note_id);

        return $this->sendRequest($request);
    }

    public function deleteListMergeField($list_id, $merge_id): void
    {
        $this->deleteListMergeFieldWithHttpInfo($list_id, $merge_id);
    }

    public function deleteListMergeFieldWithHttpInfo($list_id, $merge_id)
    {
        $request = $this->deleteListMergeFieldRequest($list_id, $merge_id);

        return $this->sendRequest($request);
    }

    public function deleteSegment($list_id, $segment_id): void
    {
        $this->deleteSegmentWithHttpInfo($list_id, $segment_id);
    }

    public function deleteSegmentWithHttpInfo($list_id, $segment_id)
    {
        $request = $this->deleteSegmentRequest($list_id, $segment_id);

        return $this->sendRequest($request);
    }

    public function removeSegmentMember($list_id, $segment_id, $subscriber_hash): void
    {
        $this->removeSegmentMemberWithHttpInfo($list_id, $segment_id, $subscriber_hash);
    }

    public function removeSegmentMemberWithHttpInfo($list_id, $segment_id, $subscriber_hash)
    {
        $request = $this->removeSegmentMemberRequest($list_id, $segment_id, $subscriber_hash);

        return $this->sendRequest($request);
    }

    public function deleteListWebhook($list_id, $webhook_id): void
    {
        $this->deleteListWebhookWithHttpInfo($list_id, $webhook_id);
    }

    public function deleteListWebhookWithHttpInfo($list_id, $webhook_id)
    {
        $request = $this->deleteListWebhookRequest($list_id, $webhook_id);

        return $this->sendRequest($request);
    }

    public function getListMemberTags($list_id, $subscriber_hash, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        return $this->getListMemberTagsWithHttpInfo($list_id, $subscriber_hash, $fields, $exclude_fields, $count, $offset);
    }

    public function getListMemberTagsWithHttpInfo($list_id, $subscriber_hash, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        $request = $this->getListMemberTagsRequest($list_id, $subscriber_hash, $fields, $exclude_fields, $count, $offset);

        return $this->sendRequest($request);
    }

    public function getAllLists($fields = null, $exclude_fields = null, $count = '10', $offset = '0', $before_date_created = null, $since_date_created = null, $before_campaign_last_sent = null, $since_campaign_last_sent = null, $email = null, $sort_field = null, $sort_dir = null, $has_ecommerce_store = null, $include_total_contacts = null)
    {
        return $this->getAllListsWithHttpInfo($fields, $exclude_fields, $count, $offset, $before_date_created, $since_date_created, $before_campaign_last_sent, $since_campaign_last_sent, $email, $sort_field, $sort_dir, $has_ecommerce_store, $include_total_contacts);
    }

    public function getAllListsWithHttpInfo($fields = null, $exclude_fields = null, $count = '10', $offset = '0', $before_date_created = null, $since_date_created = null, $before_campaign_last_sent = null, $since_campaign_last_sent = null, $email = null, $sort_field = null, $sort_dir = null, $has_ecommerce_store = null, $include_total_contacts = null)
    {
        $request = $this->getAllListsRequest($fields, $exclude_fields, $count, $offset, $before_date_created, $since_date_created, $before_campaign_last_sent, $since_campaign_last_sent, $email, $sort_field, $sort_dir, $has_ecommerce_store, $include_total_contacts);

        return $this->sendRequest($request);
    }

    public function getList($list_id, $fields = null, $exclude_fields = null, $include_total_contacts = null)
    {
        return $this->getListWithHttpInfo($list_id, $fields, $exclude_fields, $include_total_contacts);
    }

    public function getListWithHttpInfo($list_id, $fields = null, $exclude_fields = null, $include_total_contacts = null)
    {
        $request = $this->getListRequest($list_id, $fields, $exclude_fields, $include_total_contacts);

        return $this->sendRequest($request);
    }

    public function getListAbuseReports($list_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        return $this->getListAbuseReportsWithHttpInfo($list_id, $fields, $exclude_fields, $count, $offset);
    }

    public function getListAbuseReportsWithHttpInfo($list_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        $request = $this->getListAbuseReportsRequest($list_id, $fields, $exclude_fields, $count, $offset);

        return $this->sendRequest($request);
    }

    public function getListAbuseReportDetails($list_id, $report_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        return $this->getListAbuseReportDetailsWithHttpInfo($list_id, $report_id, $fields, $exclude_fields, $count, $offset);
    }

    public function getListAbuseReportDetailsWithHttpInfo($list_id, $report_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        $request = $this->getListAbuseReportDetailsRequest($list_id, $report_id, $fields, $exclude_fields, $count, $offset);

        return $this->sendRequest($request);
    }

    public function getListRecentActivity($list_id, $count = '10', $offset = '0', $fields = null, $exclude_fields = null)
    {
        return $this->getListRecentActivityWithHttpInfo($list_id, $count, $offset, $fields, $exclude_fields);
    }

    public function getListRecentActivityWithHttpInfo($list_id, $count = '10', $offset = '0', $fields = null, $exclude_fields = null)
    {
        $request = $this->getListRecentActivityRequest($list_id, $count, $offset, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getListClients($list_id, $fields = null, $exclude_fields = null)
    {
        return $this->getListClientsWithHttpInfo($list_id, $fields, $exclude_fields);
    }

    public function getListClientsWithHttpInfo($list_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getListClientsRequest($list_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getListGrowthHistory($list_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $sort_field = null, $sort_dir = null)
    {
        return $this->getListGrowthHistoryWithHttpInfo($list_id, $fields, $exclude_fields, $count, $offset, $sort_field, $sort_dir);
    }

    public function getListGrowthHistoryWithHttpInfo($list_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $sort_field = null, $sort_dir = null)
    {
        $request = $this->getListGrowthHistoryRequest($list_id, $fields, $exclude_fields, $count, $offset, $sort_field, $sort_dir);

        return $this->sendRequest($request);
    }

    public function getListGrowthHistoryByMonth($list_id, $month, $fields = null, $exclude_fields = null)
    {
        return $this->getListGrowthHistoryByMonthWithHttpInfo($list_id, $month, $fields, $exclude_fields);
    }

    public function getListGrowthHistoryByMonthWithHttpInfo($list_id, $month, $fields = null, $exclude_fields = null)
    {
        $request = $this->getListGrowthHistoryByMonthRequest($list_id, $month, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getListInterestCategories($list_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $type = null)
    {
        return $this->getListInterestCategoriesWithHttpInfo($list_id, $fields, $exclude_fields, $count, $offset, $type);
    }

    public function getListInterestCategoriesWithHttpInfo($list_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $type = null)
    {
        $request = $this->getListInterestCategoriesRequest($list_id, $fields, $exclude_fields, $count, $offset, $type);

        return $this->sendRequest($request);
    }

    public function getInterestCategory($list_id, $interest_category_id, $fields = null, $exclude_fields = null)
    {
        return $this->getInterestCategoryWithHttpInfo($list_id, $interest_category_id, $fields, $exclude_fields);
    }

    public function getInterestCategoryWithHttpInfo($list_id, $interest_category_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getInterestCategoryRequest($list_id, $interest_category_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function listInterestCategoryInterests($list_id, $interest_category_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        return $this->listInterestCategoryInterestsWithHttpInfo($list_id, $interest_category_id, $fields, $exclude_fields, $count, $offset);
    }

    public function listInterestCategoryInterestsWithHttpInfo($list_id, $interest_category_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        $request = $this->listInterestCategoryInterestsRequest($list_id, $interest_category_id, $fields, $exclude_fields, $count, $offset);

        return $this->sendRequest($request);
    }

    public function getInterestCategoryInterest($list_id, $interest_category_id, $interest_id, $fields = null, $exclude_fields = null)
    {
        return $this->getInterestCategoryInterestWithHttpInfo($list_id, $interest_category_id, $interest_id, $fields, $exclude_fields);
    }

    public function getInterestCategoryInterestWithHttpInfo($list_id, $interest_category_id, $interest_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getInterestCategoryInterestRequest($list_id, $interest_category_id, $interest_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getListLocations($list_id, $fields = null, $exclude_fields = null)
    {
        return $this->getListLocationsWithHttpInfo($list_id, $fields, $exclude_fields);
    }

    public function getListLocationsWithHttpInfo($list_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getListLocationsRequest($list_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getListMembersInfo($list_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $email_type = null, $status = null, $since_timestamp_opt = null, $before_timestamp_opt = null, $since_last_changed = null, $before_last_changed = null, $unique_email_id = null, $vip_only = null, $interest_category_id = null, $interest_ids = null, $interest_match = null, $sort_field = null, $sort_dir = null, $since_last_campaign = null, $unsubscribed_since = null)
    {
        return $this->getListMembersInfoWithHttpInfo($list_id, $fields, $exclude_fields, $count, $offset, $email_type, $status, $since_timestamp_opt, $before_timestamp_opt, $since_last_changed, $before_last_changed, $unique_email_id, $vip_only, $interest_category_id, $interest_ids, $interest_match, $sort_field, $sort_dir, $since_last_campaign, $unsubscribed_since);
    }

    public function getListMembersInfoWithHttpInfo($list_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $email_type = null, $status = null, $since_timestamp_opt = null, $before_timestamp_opt = null, $since_last_changed = null, $before_last_changed = null, $unique_email_id = null, $vip_only = null, $interest_category_id = null, $interest_ids = null, $interest_match = null, $sort_field = null, $sort_dir = null, $since_last_campaign = null, $unsubscribed_since = null)
    {
        $request = $this->getListMembersInfoRequest($list_id, $fields, $exclude_fields, $count, $offset, $email_type, $status, $since_timestamp_opt, $before_timestamp_opt, $since_last_changed, $before_last_changed, $unique_email_id, $vip_only, $interest_category_id, $interest_ids, $interest_match, $sort_field, $sort_dir, $since_last_campaign, $unsubscribed_since);

        return $this->sendRequest($request);
    }

    public function getListMember($list_id, $subscriber_hash, $fields = null, $exclude_fields = null)
    {
        return $this->getListMemberWithHttpInfo($list_id, $subscriber_hash, $fields, $exclude_fields);
    }

    public function getListMemberWithHttpInfo($list_id, $subscriber_hash, $fields = null, $exclude_fields = null)
    {
        $request = $this->getListMemberRequest($list_id, $subscriber_hash, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getListMemberActivity($list_id, $subscriber_hash, $fields = null, $exclude_fields = null, $action = null)
    {
        return $this->getListMemberActivityWithHttpInfo($list_id, $subscriber_hash, $fields, $exclude_fields, $action);
    }

    public function getListMemberActivityWithHttpInfo($list_id, $subscriber_hash, $fields = null, $exclude_fields = null, $action = null)
    {
        $request = $this->getListMemberActivityRequest($list_id, $subscriber_hash, $fields, $exclude_fields, $action);

        return $this->sendRequest($request);
    }

    public function getListMemberActivityFeed($list_id, $subscriber_hash, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $activity_filters = null)
    {
        return $this->getListMemberActivityFeedWithHttpInfo($list_id, $subscriber_hash, $fields, $exclude_fields, $count, $offset, $activity_filters);
    }

    public function getListMemberActivityFeedWithHttpInfo($list_id, $subscriber_hash, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $activity_filters = null)
    {
        $request = $this->getListMemberActivityFeedRequest($list_id, $subscriber_hash, $fields, $exclude_fields, $count, $offset, $activity_filters);

        return $this->sendRequest($request);
    }

    public function getListMemberEvents($list_id, $subscriber_hash, $count = '10', $offset = '0', $fields = null, $exclude_fields = null)
    {
        return $this->getListMemberEventsWithHttpInfo($list_id, $subscriber_hash, $count, $offset, $fields, $exclude_fields);
    }

    public function getListMemberEventsWithHttpInfo($list_id, $subscriber_hash, $count = '10', $offset = '0', $fields = null, $exclude_fields = null)
    {
        $request = $this->getListMemberEventsRequest($list_id, $subscriber_hash, $count, $offset, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getListMemberGoals($list_id, $subscriber_hash, $fields = null, $exclude_fields = null)
    {
        return $this->getListMemberGoalsWithHttpInfo($list_id, $subscriber_hash, $fields, $exclude_fields);
    }

    public function getListMemberGoalsWithHttpInfo($list_id, $subscriber_hash, $fields = null, $exclude_fields = null)
    {
        $request = $this->getListMemberGoalsRequest($list_id, $subscriber_hash, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getListMemberNotes($list_id, $subscriber_hash, $sort_field = null, $sort_dir = null, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        return $this->getListMemberNotesWithHttpInfo($list_id, $subscriber_hash, $sort_field, $sort_dir, $fields, $exclude_fields, $count, $offset);
    }

    public function getListMemberNotesWithHttpInfo($list_id, $subscriber_hash, $sort_field = null, $sort_dir = null, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        $request = $this->getListMemberNotesRequest($list_id, $subscriber_hash, $sort_field, $sort_dir, $fields, $exclude_fields, $count, $offset);

        return $this->sendRequest($request);
    }

    public function getListMemberNote($list_id, $subscriber_hash, $note_id, $fields = null, $exclude_fields = null)
    {
        return $this->getListMemberNoteWithHttpInfo($list_id, $subscriber_hash, $note_id, $fields, $exclude_fields);
    }

    public function getListMemberNoteWithHttpInfo($list_id, $subscriber_hash, $note_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getListMemberNoteRequest($list_id, $subscriber_hash, $note_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getListMergeFields($list_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $type = null, $required = null)
    {
        return $this->getListMergeFieldsWithHttpInfo($list_id, $fields, $exclude_fields, $count, $offset, $type, $required);
    }

    public function getListMergeFieldsWithHttpInfo($list_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $type = null, $required = null)
    {
        $request = $this->getListMergeFieldsRequest($list_id, $fields, $exclude_fields, $count, $offset, $type, $required);

        return $this->sendRequest($request);
    }

    public function getListMergeField($list_id, $merge_id, $exclude_fields = null, $fields = null)
    {
        return $this->getListMergeFieldWithHttpInfo($list_id, $merge_id, $exclude_fields, $fields);
    }

    public function getListMergeFieldWithHttpInfo($list_id, $merge_id, $exclude_fields = null, $fields = null)
    {
        $request = $this->getListMergeFieldRequest($list_id, $merge_id, $exclude_fields, $fields);

        return $this->sendRequest($request);
    }

    public function getSegment($list_id, $segment_id, $fields = null, $exclude_fields = null, $include_cleaned = null, $include_transactional = null, $include_unsubscribed = null)
    {
        return $this->getSegmentWithHttpInfo($list_id, $segment_id, $fields, $exclude_fields, $include_cleaned, $include_transactional, $include_unsubscribed);
    }

    public function getSegmentWithHttpInfo($list_id, $segment_id, $fields = null, $exclude_fields = null, $include_cleaned = null, $include_transactional = null, $include_unsubscribed = null)
    {
        $request = $this->getSegmentRequest($list_id, $segment_id, $fields, $exclude_fields, $include_cleaned, $include_transactional, $include_unsubscribed);

        return $this->sendRequest($request);
    }

    public function getSegmentMembersList($list_id, $segment_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $include_cleaned = null, $include_transactional = null, $include_unsubscribed = null)
    {
        return $this->getSegmentMembersListWithHttpInfo($list_id, $segment_id, $fields, $exclude_fields, $count, $offset, $include_cleaned, $include_transactional, $include_unsubscribed);
    }

    public function getSegmentMembersListWithHttpInfo($list_id, $segment_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $include_cleaned = null, $include_transactional = null, $include_unsubscribed = null)
    {
        $request = $this->getSegmentMembersListRequest($list_id, $segment_id, $fields, $exclude_fields, $count, $offset, $include_cleaned, $include_transactional, $include_unsubscribed);

        return $this->sendRequest($request);
    }

    public function getListSignupForms($list_id)
    {
        return $this->getListSignupFormsWithHttpInfo($list_id);
    }

    public function getListSignupFormsWithHttpInfo($list_id)
    {
        $request = $this->getListSignupFormsRequest($list_id);

        return $this->sendRequest($request);
    }

    public function getAllSurveysForList($list_id): void
    {
        $this->getAllSurveysForListWithHttpInfo($list_id);
    }

    public function getAllSurveysForListWithHttpInfo($list_id)
    {
        $request = $this->getAllSurveysForListRequest($list_id);

        return $this->sendRequest($request);
    }

    public function getSurvey($list_id, $survey_id): void
    {
        $this->getSurveyWithHttpInfo($list_id, $survey_id);
    }

    public function getSurveyWithHttpInfo($list_id, $survey_id)
    {
        $request = $this->getSurveyRequest($list_id, $survey_id);

        return $this->sendRequest($request);
    }

    public function getListWebhooks($list_id)
    {
        return $this->getListWebhooksWithHttpInfo($list_id);
    }

    public function getListWebhooksWithHttpInfo($list_id)
    {
        $request = $this->getListWebhooksRequest($list_id);

        return $this->sendRequest($request);
    }

    public function getListWebhook($list_id, $webhook_id)
    {
        return $this->getListWebhookWithHttpInfo($list_id, $webhook_id);
    }

    public function getListWebhookWithHttpInfo($list_id, $webhook_id)
    {
        $request = $this->getListWebhookRequest($list_id, $webhook_id);

        return $this->sendRequest($request);
    }

    public function updateList($list_id, $body)
    {
        return $this->updateListWithHttpInfo($list_id, $body);
    }

    public function updateListWithHttpInfo($list_id, $body)
    {
        $request = $this->updateListRequest($list_id, $body);

        return $this->sendRequest($request);
    }

    public function updateInterestCategory($list_id, $interest_category_id, $body)
    {
        return $this->updateInterestCategoryWithHttpInfo($list_id, $interest_category_id, $body);
    }

    public function updateInterestCategoryWithHttpInfo($list_id, $interest_category_id, $body)
    {
        $request = $this->updateInterestCategoryRequest($list_id, $interest_category_id, $body);

        return $this->sendRequest($request);
    }

    public function updateInterestCategoryInterest($list_id, $interest_category_id, $interest_id, $body)
    {
        return $this->updateInterestCategoryInterestWithHttpInfo($list_id, $interest_category_id, $interest_id, $body);
    }

    public function updateInterestCategoryInterestWithHttpInfo($list_id, $interest_category_id, $interest_id, $body)
    {
        $request = $this->updateInterestCategoryInterestRequest($list_id, $interest_category_id, $interest_id, $body);

        return $this->sendRequest($request);
    }

    public function updateListMember($list_id, $subscriber_hash, $body, $skip_merge_validation = null)
    {
        return $this->updateListMemberWithHttpInfo($list_id, $subscriber_hash, $body, $skip_merge_validation);
    }

    public function updateListMemberWithHttpInfo($list_id, $subscriber_hash, $body, $skip_merge_validation = null)
    {
        $request = $this->updateListMemberRequest($list_id, $subscriber_hash, $body, $skip_merge_validation);

        return $this->sendRequest($request);
    }

    public function updateListMemberNote($list_id, $subscriber_hash, $note_id, $body)
    {
        return $this->updateListMemberNoteWithHttpInfo($list_id, $subscriber_hash, $note_id, $body);
    }

    public function updateListMemberNoteWithHttpInfo($list_id, $subscriber_hash, $note_id, $body)
    {
        $request = $this->updateListMemberNoteRequest($list_id, $subscriber_hash, $note_id, $body);

        return $this->sendRequest($request);
    }

    public function updateListMergeField($list_id, $merge_id, $body)
    {
        return $this->updateListMergeFieldWithHttpInfo($list_id, $merge_id, $body);
    }

    public function updateListMergeFieldWithHttpInfo($list_id, $merge_id, $body)
    {
        $request = $this->updateListMergeFieldRequest($list_id, $merge_id, $body);

        return $this->sendRequest($request);
    }

    public function updateSegment($list_id, $segment_id, $body)
    {
        return $this->updateSegmentWithHttpInfo($list_id, $segment_id, $body);
    }

    public function updateSegmentWithHttpInfo($list_id, $segment_id, $body)
    {
        $request = $this->updateSegmentRequest($list_id, $segment_id, $body);

        return $this->sendRequest($request);
    }

    public function updateListWebhook($list_id, $webhook_id, $body)
    {
        return $this->updateListWebhookWithHttpInfo($list_id, $webhook_id, $body);
    }

    public function updateListWebhookWithHttpInfo($list_id, $webhook_id, $body)
    {
        $request = $this->updateListWebhookRequest($list_id, $webhook_id, $body);

        return $this->sendRequest($request);
    }

    public function createListMemberEvent($list_id, $subscriber_hash, $body): void
    {
        $this->createListMemberEventWithHttpInfo($list_id, $subscriber_hash, $body);
    }

    public function createListMemberEventWithHttpInfo($list_id, $subscriber_hash, $body)
    {
        $request = $this->createListMemberEventRequest($list_id, $subscriber_hash, $body);

        return $this->sendRequest($request);
    }

    public function updateListMemberTags($list_id, $subscriber_hash, $body): void
    {
        $this->updateListMemberTagsWithHttpInfo($list_id, $subscriber_hash, $body);
    }

    public function updateListMemberTagsWithHttpInfo($list_id, $subscriber_hash, $body)
    {
        $request = $this->updateListMemberTagsRequest($list_id, $subscriber_hash, $body);

        return $this->sendRequest($request);
    }

    public function createList($body)
    {
        return $this->createListWithHttpInfo($body);
    }

    public function createListWithHttpInfo($body)
    {
        $request = $this->createListRequest($body);

        return $this->sendRequest($request);
    }

    public function batchListMembers($list_id, $body, $skip_merge_validation = null, $skip_duplicate_check = null)
    {
        return $this->batchListMembersWithHttpInfo($list_id, $body, $skip_merge_validation, $skip_duplicate_check);
    }

    public function batchListMembersWithHttpInfo($list_id, $body, $skip_merge_validation = null, $skip_duplicate_check = null)
    {
        $request = $this->batchListMembersRequest($list_id, $body, $skip_merge_validation, $skip_duplicate_check);

        return $this->sendRequest($request);
    }

    public function createListInterestCategory($list_id, $body)
    {
        return $this->createListInterestCategoryWithHttpInfo($list_id, $body);
    }

    public function createListInterestCategoryWithHttpInfo($list_id, $body)
    {
        $request = $this->createListInterestCategoryRequest($list_id, $body);

        return $this->sendRequest($request);
    }

    public function createInterestCategoryInterest($list_id, $interest_category_id, $body)
    {
        return $this->createInterestCategoryInterestWithHttpInfo($list_id, $interest_category_id, $body);
    }

    public function createInterestCategoryInterestWithHttpInfo($list_id, $interest_category_id, $body)
    {
        $request = $this->createInterestCategoryInterestRequest($list_id, $interest_category_id, $body);

        return $this->sendRequest($request);
    }

    public function addListMember($list_id, $body, $skip_merge_validation = null)
    {
        return $this->addListMemberWithHttpInfo($list_id, $body, $skip_merge_validation);
    }

    public function addListMemberWithHttpInfo($list_id, $body, $skip_merge_validation = null)
    {
        $request = $this->addListMemberRequest($list_id, $body, $skip_merge_validation);

        return $this->sendRequest($request);
    }

    public function deleteListMemberPermanent($list_id, $subscriber_hash): void
    {
        $this->deleteListMemberPermanentWithHttpInfo($list_id, $subscriber_hash);
    }

    public function deleteListMemberPermanentWithHttpInfo($list_id, $subscriber_hash)
    {
        $request = $this->deleteListMemberPermanentRequest($list_id, $subscriber_hash);

        return $this->sendRequest($request);
    }

    public function createListMemberNote($list_id, $subscriber_hash, $body)
    {
        return $this->createListMemberNoteWithHttpInfo($list_id, $subscriber_hash, $body);
    }

    public function createListMemberNoteWithHttpInfo($list_id, $subscriber_hash, $body)
    {
        $request = $this->createListMemberNoteRequest($list_id, $subscriber_hash, $body);

        return $this->sendRequest($request);
    }

    public function addListMergeField($list_id, $body)
    {
        return $this->addListMergeFieldWithHttpInfo($list_id, $body);
    }

    public function addListMergeFieldWithHttpInfo($list_id, $body)
    {
        $request = $this->addListMergeFieldRequest($list_id, $body);

        return $this->sendRequest($request);
    }

    public function createSegment($list_id, $body)
    {
        return $this->createSegmentWithHttpInfo($list_id, $body);
    }

    public function createSegmentWithHttpInfo($list_id, $body)
    {
        $request = $this->createSegmentRequest($list_id, $body);

        return $this->sendRequest($request);
    }

    public function batchSegmentMembers($body, $list_id, $segment_id)
    {
        return $this->batchSegmentMembersWithHttpInfo($body, $list_id, $segment_id);
    }

    public function batchSegmentMembersWithHttpInfo($body, $list_id, $segment_id)
    {
        $request = $this->batchSegmentMembersRequest($body, $list_id, $segment_id);

        return $this->sendRequest($request);
    }

    public function createSegmentMember($list_id, $segment_id, $body)
    {
        return $this->createSegmentMemberWithHttpInfo($list_id, $segment_id, $body);
    }

    public function createSegmentMemberWithHttpInfo($list_id, $segment_id, $body)
    {
        $request = $this->createSegmentMemberRequest($list_id, $segment_id, $body);

        return $this->sendRequest($request);
    }

    public function updateListSignupForm($list_id, $body)
    {
        return $this->updateListSignupFormWithHttpInfo($list_id, $body);
    }

    public function updateListSignupFormWithHttpInfo($list_id, $body)
    {
        $request = $this->updateListSignupFormRequest($list_id, $body);

        return $this->sendRequest($request);
    }

    public function createListWebhook($list_id, $body)
    {
        return $this->createListWebhookWithHttpInfo($list_id, $body);
    }

    public function createListWebhookWithHttpInfo($list_id, $body)
    {
        $request = $this->createListWebhookRequest($list_id, $body);

        return $this->sendRequest($request);
    }

    public function listSegments($list_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $type = null, $since_created_at = null, $before_created_at = null, $include_cleaned = null, $include_transactional = null, $include_unsubscribed = null, $since_updated_at = null, $before_updated_at = null)
    {
        return $this->listSegmentsWithHttpInfo($list_id, $fields, $exclude_fields, $count, $offset, $type, $since_created_at, $before_created_at, $include_cleaned, $include_transactional, $include_unsubscribed, $since_updated_at, $before_updated_at);
    }

    public function listSegmentsWithHttpInfo($list_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $type = null, $since_created_at = null, $before_created_at = null, $include_cleaned = null, $include_transactional = null, $include_unsubscribed = null, $since_updated_at = null, $before_updated_at = null)
    {
        $request = $this->listSegmentsRequest($list_id, $fields, $exclude_fields, $count, $offset, $type, $since_created_at, $before_created_at, $include_cleaned, $include_transactional, $include_unsubscribed, $since_updated_at, $before_updated_at);

        return $this->sendRequest($request);
    }

    public function setListMember($list_id, $subscriber_hash, $body, $skip_merge_validation = null)
    {
        return $this->setListMemberWithHttpInfo($list_id, $subscriber_hash, $body, $skip_merge_validation);
    }

    public function setListMemberWithHttpInfo($list_id, $subscriber_hash, $body, $skip_merge_validation = null)
    {
        $request = $this->setListMemberRequest($list_id, $subscriber_hash, $body, $skip_merge_validation);

        return $this->sendRequest($request);
    }

    public function tagSearch($list_id, $name = null)
    {
        return $this->tagSearchWithHttpInfo($list_id, $name);
    }

    public function tagSearchWithHttpInfo($list_id, $name = null)
    {
        $request = $this->tagSearchRequest($list_id, $name);

        return $this->sendRequest($request);
    }

    protected function deleteListRequest($list_id): Request
    {
        $this->requireParam($list_id, 'list_id');

        $resourcePath = '/lists/{list_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);

        return $this->buildRequest('DELETE', $resourcePath, $queryParams);
    }

    protected function deleteInterestCategoryRequest($list_id, $interest_category_id): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($interest_category_id, 'interest_category_id');

        $resourcePath = '/lists/{list_id}/interest-categories/{interest_category_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'interest_category_id', $interest_category_id);

        return $this->buildRequest('DELETE', $resourcePath, $queryParams);
    }

    protected function deleteInterestCategoryInterestRequest($list_id, $interest_category_id, $interest_id): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($interest_category_id, 'interest_category_id');
        $this->requireParam($interest_id, 'interest_id');

        $resourcePath = '/lists/{list_id}/interest-categories/{interest_category_id}/interests/{interest_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'interest_category_id', $interest_category_id);
        $this->replacePathParam($resourcePath, 'interest_id', $interest_id);

        return $this->buildRequest('DELETE', $resourcePath, $queryParams);
    }

    protected function deleteListMemberRequest($list_id, $subscriber_hash): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($subscriber_hash, 'subscriber_hash');

        $resourcePath = '/lists/{list_id}/members/{subscriber_hash}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'subscriber_hash', $subscriber_hash);

        return $this->buildRequest('DELETE', $resourcePath, $queryParams);
    }

    protected function deleteListMemberNoteRequest($list_id, $subscriber_hash, $note_id): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($subscriber_hash, 'subscriber_hash');
        $this->requireParam($note_id, 'note_id');

        $resourcePath = '/lists/{list_id}/members/{subscriber_hash}/notes/{note_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'subscriber_hash', $subscriber_hash);
        $this->replacePathParam($resourcePath, 'note_id', $note_id);

        return $this->buildRequest('DELETE', $resourcePath, $queryParams);
    }

    protected function deleteListMergeFieldRequest($list_id, $merge_id): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($merge_id, 'merge_id');

        $resourcePath = '/lists/{list_id}/merge-fields/{merge_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'merge_id', $merge_id);

        return $this->buildRequest('DELETE', $resourcePath, $queryParams);
    }

    protected function deleteSegmentRequest($list_id, $segment_id): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($segment_id, 'segment_id');

        $resourcePath = '/lists/{list_id}/segments/{segment_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'segment_id', $segment_id);

        return $this->buildRequest('DELETE', $resourcePath, $queryParams);
    }

    protected function removeSegmentMemberRequest($list_id, $segment_id, $subscriber_hash): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($segment_id, 'segment_id');
        $this->requireParam($subscriber_hash, 'subscriber_hash');

        $resourcePath = '/lists/{list_id}/segments/{segment_id}/members/{subscriber_hash}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'segment_id', $segment_id);
        $this->replacePathParam($resourcePath, 'subscriber_hash', $subscriber_hash);

        return $this->buildRequest('DELETE', $resourcePath, $queryParams);
    }

    protected function deleteListWebhookRequest($list_id, $webhook_id): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($webhook_id, 'webhook_id');

        $resourcePath = '/lists/{list_id}/webhooks/{webhook_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'webhook_id', $webhook_id);

        return $this->buildRequest('DELETE', $resourcePath, $queryParams);
    }

    protected function getListMemberTagsRequest($list_id, $subscriber_hash, $fields = null, $exclude_fields = null, $count = '10', $offset = '0'): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($subscriber_hash, 'subscriber_hash');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ListsApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/lists/{list_id}/members/{subscriber_hash}/tags';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'subscriber_hash', $subscriber_hash);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getAllListsRequest($fields = null, $exclude_fields = null, $count = '10', $offset = '0', $before_date_created = null, $since_date_created = null, $before_campaign_last_sent = null, $since_campaign_last_sent = null, $email = null, $sort_field = null, $sort_dir = null, $has_ecommerce_store = null, $include_total_contacts = null): Request
    {
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ListsApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/lists';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);
        $this->addQueryParam($queryParams, 'before_date_created', $before_date_created);
        $this->addQueryParam($queryParams, 'since_date_created', $since_date_created);
        $this->addQueryParam($queryParams, 'before_campaign_last_sent', $before_campaign_last_sent);
        $this->addQueryParam($queryParams, 'since_campaign_last_sent', $since_campaign_last_sent);
        $this->addQueryParam($queryParams, 'email', $email);
        $this->addQueryParam($queryParams, 'sort_field', $sort_field);
        $this->addQueryParam($queryParams, 'sort_dir', $sort_dir);
        $this->addQueryParam($queryParams, 'has_ecommerce_store', $has_ecommerce_store);
        $this->addQueryParam($queryParams, 'include_total_contacts', $include_total_contacts);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getListRequest($list_id, $fields = null, $exclude_fields = null, $include_total_contacts = null): Request
    {
        $this->requireParam($list_id, 'list_id');

        $resourcePath = '/lists/{list_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);
        $this->addQueryParam($queryParams, 'include_total_contacts', $include_total_contacts);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getListAbuseReportsRequest($list_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0'): Request
    {
        $this->requireParam($list_id, 'list_id');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ListsApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/lists/{list_id}/abuse-reports';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getListAbuseReportDetailsRequest($list_id, $report_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0'): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($report_id, 'report_id');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ListsApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/lists/{list_id}/abuse-reports/{report_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'report_id', $report_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getListRecentActivityRequest($list_id, $count = '10', $offset = '0', $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($list_id, 'list_id');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ListsApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/lists/{list_id}/activity';
        $queryParams = [];
        $this->addQueryParam($queryParams, 'count', $count);
        $this->addQueryParam($queryParams, 'offset', $offset);
        $this->addQueryParam($queryParams, 'fields', $fields);
        $this->addQueryParam($queryParams, 'exclude_fields', $exclude_fields);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getListClientsRequest($list_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($list_id, 'list_id');

        $resourcePath = '/lists/{list_id}/clients';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getListGrowthHistoryRequest($list_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $sort_field = null, $sort_dir = null): Request
    {
        $this->requireParam($list_id, 'list_id');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ListsApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/lists/{list_id}/growth-history';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);
        $this->addQueryParam($queryParams, 'sort_field', $sort_field);
        $this->addQueryParam($queryParams, 'sort_dir', $sort_dir);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getListGrowthHistoryByMonthRequest($list_id, $month, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($month, 'month');

        $resourcePath = '/lists/{list_id}/growth-history/{month}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'month', $month);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getListInterestCategoriesRequest($list_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $type = null): Request
    {
        $this->requireParam($list_id, 'list_id');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ListsApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/lists/{list_id}/interest-categories';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);
        $this->addQueryParam($queryParams, 'type', $type);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getInterestCategoryRequest($list_id, $interest_category_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($interest_category_id, 'interest_category_id');

        $resourcePath = '/lists/{list_id}/interest-categories/{interest_category_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'interest_category_id', $interest_category_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function listInterestCategoryInterestsRequest($list_id, $interest_category_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0'): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($interest_category_id, 'interest_category_id');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ListsApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/lists/{list_id}/interest-categories/{interest_category_id}/interests';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'interest_category_id', $interest_category_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getInterestCategoryInterestRequest($list_id, $interest_category_id, $interest_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($interest_category_id, 'interest_category_id');
        $this->requireParam($interest_id, 'interest_id');

        $resourcePath = '/lists/{list_id}/interest-categories/{interest_category_id}/interests/{interest_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'interest_category_id', $interest_category_id);
        $this->replacePathParam($resourcePath, 'interest_id', $interest_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getListLocationsRequest($list_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($list_id, 'list_id');

        $resourcePath = '/lists/{list_id}/locations';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getListMembersInfoRequest($list_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $email_type = null, $status = null, $since_timestamp_opt = null, $before_timestamp_opt = null, $since_last_changed = null, $before_last_changed = null, $unique_email_id = null, $vip_only = null, $interest_category_id = null, $interest_ids = null, $interest_match = null, $sort_field = null, $sort_dir = null, $since_last_campaign = null, $unsubscribed_since = null): Request
    {
        $this->requireParam($list_id, 'list_id');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ListsApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/lists/{list_id}/members';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);
        $this->addQueryParam($queryParams, 'email_type', $email_type);
        $this->addQueryParam($queryParams, 'status', $status);
        $this->addQueryParam($queryParams, 'since_timestamp_opt', $since_timestamp_opt);
        $this->addQueryParam($queryParams, 'before_timestamp_opt', $before_timestamp_opt);
        $this->addQueryParam($queryParams, 'since_last_changed', $since_last_changed);
        $this->addQueryParam($queryParams, 'before_last_changed', $before_last_changed);
        $this->addQueryParam($queryParams, 'unique_email_id', $unique_email_id);
        $this->addQueryParam($queryParams, 'vip_only', $vip_only);
        $this->addQueryParam($queryParams, 'interest_category_id', $interest_category_id);
        $this->addQueryParam($queryParams, 'interest_ids', $interest_ids);
        $this->addQueryParam($queryParams, 'interest_match', $interest_match);
        $this->addQueryParam($queryParams, 'sort_field', $sort_field);
        $this->addQueryParam($queryParams, 'sort_dir', $sort_dir);
        $this->addQueryParam($queryParams, 'since_last_campaign', $since_last_campaign);
        $this->addQueryParam($queryParams, 'unsubscribed_since', $unsubscribed_since);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getListMemberRequest($list_id, $subscriber_hash, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($subscriber_hash, 'subscriber_hash');

        $resourcePath = '/lists/{list_id}/members/{subscriber_hash}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'subscriber_hash', $subscriber_hash);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getListMemberActivityRequest($list_id, $subscriber_hash, $fields = null, $exclude_fields = null, $action = null): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($subscriber_hash, 'subscriber_hash');

        $resourcePath = '/lists/{list_id}/members/{subscriber_hash}/activity';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);
        $this->addQueryParam($queryParams, 'action', $action);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'subscriber_hash', $subscriber_hash);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getListMemberActivityFeedRequest($list_id, $subscriber_hash, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $activity_filters = null): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($subscriber_hash, 'subscriber_hash');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ListsApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/lists/{list_id}/members/{subscriber_hash}/activity-feed';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);
        $this->addQueryParam($queryParams, 'activity_filters', $activity_filters);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'subscriber_hash', $subscriber_hash);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getListMemberEventsRequest($list_id, $subscriber_hash, $count = '10', $offset = '0', $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($subscriber_hash, 'subscriber_hash');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ListsApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/lists/{list_id}/members/{subscriber_hash}/events';
        $queryParams = [];
        $this->addQueryParam($queryParams, 'count', $count);
        $this->addQueryParam($queryParams, 'offset', $offset);
        $this->addQueryParam($queryParams, 'fields', $fields);
        $this->addQueryParam($queryParams, 'exclude_fields', $exclude_fields);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'subscriber_hash', $subscriber_hash);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getListMemberGoalsRequest($list_id, $subscriber_hash, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($subscriber_hash, 'subscriber_hash');

        $resourcePath = '/lists/{list_id}/members/{subscriber_hash}/goals';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'subscriber_hash', $subscriber_hash);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getListMemberNotesRequest($list_id, $subscriber_hash, $sort_field = null, $sort_dir = null, $fields = null, $exclude_fields = null, $count = '10', $offset = '0'): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($subscriber_hash, 'subscriber_hash');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ListsApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/lists/{list_id}/members/{subscriber_hash}/notes';
        $queryParams = [];
        $this->addQueryParam($queryParams, 'sort_field', $sort_field);
        $this->addQueryParam($queryParams, 'sort_dir', $sort_dir);
        $this->addQueryParam($queryParams, 'fields', $fields);
        $this->addQueryParam($queryParams, 'exclude_fields', $exclude_fields);
        $this->addQueryParam($queryParams, 'count', $count);
        $this->addQueryParam($queryParams, 'offset', $offset);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'subscriber_hash', $subscriber_hash);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getListMemberNoteRequest($list_id, $subscriber_hash, $note_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($subscriber_hash, 'subscriber_hash');
        $this->requireParam($note_id, 'note_id');

        $resourcePath = '/lists/{list_id}/members/{subscriber_hash}/notes/{note_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'subscriber_hash', $subscriber_hash);
        $this->replacePathParam($resourcePath, 'note_id', $note_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getListMergeFieldsRequest($list_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $type = null, $required = null): Request
    {
        $this->requireParam($list_id, 'list_id');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ListsApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/lists/{list_id}/merge-fields';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);
        $this->addQueryParam($queryParams, 'type', $type);
        $this->addQueryParam($queryParams, 'required', $required);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getListMergeFieldRequest($list_id, $merge_id, $exclude_fields = null, $fields = null): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($merge_id, 'merge_id');

        $resourcePath = '/lists/{list_id}/merge-fields/{merge_id}';
        $queryParams = [];
        $this->addQueryParam($queryParams, 'exclude_fields', $exclude_fields);
        $this->addQueryParam($queryParams, 'fields', $fields);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'merge_id', $merge_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getSegmentRequest($list_id, $segment_id, $fields = null, $exclude_fields = null, $include_cleaned = null, $include_transactional = null, $include_unsubscribed = null): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($segment_id, 'segment_id');

        $resourcePath = '/lists/{list_id}/segments/{segment_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);
        $this->addQueryParam($queryParams, 'include_cleaned', $include_cleaned);
        $this->addQueryParam($queryParams, 'include_transactional', $include_transactional);
        $this->addQueryParam($queryParams, 'include_unsubscribed', $include_unsubscribed);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'segment_id', $segment_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getSegmentMembersListRequest($list_id, $segment_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $include_cleaned = null, $include_transactional = null, $include_unsubscribed = null): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($segment_id, 'segment_id');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ListsApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/lists/{list_id}/segments/{segment_id}/members';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);
        $this->addQueryParam($queryParams, 'include_cleaned', $include_cleaned);
        $this->addQueryParam($queryParams, 'include_transactional', $include_transactional);
        $this->addQueryParam($queryParams, 'include_unsubscribed', $include_unsubscribed);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'segment_id', $segment_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getListSignupFormsRequest($list_id): Request
    {
        $this->requireParam($list_id, 'list_id');

        $resourcePath = '/lists/{list_id}/signup-forms';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getAllSurveysForListRequest($list_id): Request
    {
        $this->requireParam($list_id, 'list_id');

        $resourcePath = '/lists/{list_id}/surveys';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getSurveyRequest($list_id, $survey_id): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($survey_id, 'survey_id');

        $resourcePath = '/lists/{list_id}/surveys/{survey_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'survey_id', $survey_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getListWebhooksRequest($list_id): Request
    {
        $this->requireParam($list_id, 'list_id');

        $resourcePath = '/lists/{list_id}/webhooks';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getListWebhookRequest($list_id, $webhook_id): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($webhook_id, 'webhook_id');

        $resourcePath = '/lists/{list_id}/webhooks/{webhook_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'webhook_id', $webhook_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function updateListRequest($list_id, $body): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/lists/{list_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);

        return $this->buildRequest('PATCH', $resourcePath, $queryParams, $body);
    }

    protected function updateInterestCategoryRequest($list_id, $interest_category_id, $body): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($interest_category_id, 'interest_category_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/lists/{list_id}/interest-categories/{interest_category_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'interest_category_id', $interest_category_id);

        return $this->buildRequest('PATCH', $resourcePath, $queryParams, $body);
    }

    protected function updateInterestCategoryInterestRequest($list_id, $interest_category_id, $interest_id, $body): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($interest_category_id, 'interest_category_id');
        $this->requireParam($interest_id, 'interest_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/lists/{list_id}/interest-categories/{interest_category_id}/interests/{interest_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'interest_category_id', $interest_category_id);
        $this->replacePathParam($resourcePath, 'interest_id', $interest_id);

        return $this->buildRequest('PATCH', $resourcePath, $queryParams, $body);
    }

    protected function updateListMemberRequest($list_id, $subscriber_hash, $body, $skip_merge_validation = null): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($subscriber_hash, 'subscriber_hash');
        $this->requireParam($body, 'body');

        $resourcePath = '/lists/{list_id}/members/{subscriber_hash}';
        $queryParams = [];
        $this->addQueryParam($queryParams, 'skip_merge_validation', $skip_merge_validation);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'subscriber_hash', $subscriber_hash);

        return $this->buildRequest('PATCH', $resourcePath, $queryParams, $body);
    }

    protected function updateListMemberNoteRequest($list_id, $subscriber_hash, $note_id, $body): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($subscriber_hash, 'subscriber_hash');
        $this->requireParam($note_id, 'note_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/lists/{list_id}/members/{subscriber_hash}/notes/{note_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'subscriber_hash', $subscriber_hash);
        $this->replacePathParam($resourcePath, 'note_id', $note_id);

        return $this->buildRequest('PATCH', $resourcePath, $queryParams, $body);
    }

    protected function updateListMergeFieldRequest($list_id, $merge_id, $body): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($merge_id, 'merge_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/lists/{list_id}/merge-fields/{merge_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'merge_id', $merge_id);

        return $this->buildRequest('PATCH', $resourcePath, $queryParams, $body);
    }

    protected function updateSegmentRequest($list_id, $segment_id, $body): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($segment_id, 'segment_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/lists/{list_id}/segments/{segment_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'segment_id', $segment_id);

        return $this->buildRequest('PATCH', $resourcePath, $queryParams, $body);
    }

    protected function updateListWebhookRequest($list_id, $webhook_id, $body): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($webhook_id, 'webhook_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/lists/{list_id}/webhooks/{webhook_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'webhook_id', $webhook_id);

        return $this->buildRequest('PATCH', $resourcePath, $queryParams, $body);
    }

    protected function createListMemberEventRequest($list_id, $subscriber_hash, $body): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($subscriber_hash, 'subscriber_hash');
        $this->requireParam($body, 'body');

        $resourcePath = '/lists/{list_id}/members/{subscriber_hash}/events';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'subscriber_hash', $subscriber_hash);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function updateListMemberTagsRequest($list_id, $subscriber_hash, $body): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($subscriber_hash, 'subscriber_hash');
        $this->requireParam($body, 'body');

        $resourcePath = '/lists/{list_id}/members/{subscriber_hash}/tags';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'subscriber_hash', $subscriber_hash);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function createListRequest($body): Request
    {
        $this->requireParam($body, 'body');

        $resourcePath = '/lists';
        $queryParams = [];

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function batchListMembersRequest($list_id, $body, $skip_merge_validation = null, $skip_duplicate_check = null): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/lists/{list_id}';
        $queryParams = [];
        $this->addQueryParam($queryParams, 'skip_merge_validation', $skip_merge_validation);
        $this->addQueryParam($queryParams, 'skip_duplicate_check', $skip_duplicate_check);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function createListInterestCategoryRequest($list_id, $body): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/lists/{list_id}/interest-categories';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function createInterestCategoryInterestRequest($list_id, $interest_category_id, $body): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($interest_category_id, 'interest_category_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/lists/{list_id}/interest-categories/{interest_category_id}/interests';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'interest_category_id', $interest_category_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function addListMemberRequest($list_id, $body, $skip_merge_validation = null): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/lists/{list_id}/members';
        $queryParams = [];
        $this->addQueryParam($queryParams, 'skip_merge_validation', $skip_merge_validation);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function deleteListMemberPermanentRequest($list_id, $subscriber_hash): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($subscriber_hash, 'subscriber_hash');

        $resourcePath = '/lists/{list_id}/members/{subscriber_hash}/actions/delete-permanent';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'subscriber_hash', $subscriber_hash);

        return $this->buildRequest('POST', $resourcePath, $queryParams);
    }

    protected function createListMemberNoteRequest($list_id, $subscriber_hash, $body): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($subscriber_hash, 'subscriber_hash');
        $this->requireParam($body, 'body');

        $resourcePath = '/lists/{list_id}/members/{subscriber_hash}/notes';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'subscriber_hash', $subscriber_hash);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function addListMergeFieldRequest($list_id, $body): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/lists/{list_id}/merge-fields';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function createSegmentRequest($list_id, $body): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/lists/{list_id}/segments';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function batchSegmentMembersRequest($body, $list_id, $segment_id): Request
    {
        $this->requireParam($body, 'body');
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($segment_id, 'segment_id');

        $resourcePath = '/lists/{list_id}/segments/{segment_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'segment_id', $segment_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function createSegmentMemberRequest($list_id, $segment_id, $body): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($segment_id, 'segment_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/lists/{list_id}/segments/{segment_id}/members';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'segment_id', $segment_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function updateListSignupFormRequest($list_id, $body): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/lists/{list_id}/signup-forms';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function createListWebhookRequest($list_id, $body): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/lists/{list_id}/webhooks';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function listSegmentsRequest($list_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $type = null, $since_created_at = null, $before_created_at = null, $include_cleaned = null, $include_transactional = null, $include_unsubscribed = null, $since_updated_at = null, $before_updated_at = null): Request
    {
        $this->requireParam($list_id, 'list_id');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ListsApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/lists/{list_id}/segments';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);
        $this->addQueryParam($queryParams, 'type', $type);
        $this->addQueryParam($queryParams, 'since_created_at', $since_created_at);
        $this->addQueryParam($queryParams, 'before_created_at', $before_created_at);
        $this->addQueryParam($queryParams, 'include_cleaned', $include_cleaned);
        $this->addQueryParam($queryParams, 'include_transactional', $include_transactional);
        $this->addQueryParam($queryParams, 'include_unsubscribed', $include_unsubscribed);
        $this->addQueryParam($queryParams, 'since_updated_at', $since_updated_at);
        $this->addQueryParam($queryParams, 'before_updated_at', $before_updated_at);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function setListMemberRequest($list_id, $subscriber_hash, $body, $skip_merge_validation = null): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($subscriber_hash, 'subscriber_hash');
        $this->requireParam($body, 'body');

        $resourcePath = '/lists/{list_id}/members/{subscriber_hash}';
        $queryParams = [];
        $this->addQueryParam($queryParams, 'skip_merge_validation', $skip_merge_validation);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'subscriber_hash', $subscriber_hash);

        return $this->buildRequest('PUT', $resourcePath, $queryParams, $body);
    }

    protected function tagSearchRequest($list_id, $name = null): Request
    {
        $this->requireParam($list_id, 'list_id');

        $resourcePath = '/lists/{list_id}/tag-search';
        $queryParams = [];
        $this->addQueryParam($queryParams, 'name', $name);

        $this->replacePathParam($resourcePath, 'list_id', $list_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }
}
