<?php

declare(strict_types=1);

/**
 * ReportingApi
 * PHP version 5.
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mailchimp Marketing API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.80
 * Contact: apihelp@mailchimp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MailchimpMarketing\Api;

use GuzzleHttp\Psr7\Request;

class ReportingApi extends AbstractApi
{
    public function getFacebookAdsReportAll($fields = null, $exclude_fields = null, $count = '10', $offset = '0', $sort_field = null, $sort_dir = null)
    {
        return $this->getFacebookAdsReportAllWithHttpInfo($fields, $exclude_fields, $count, $offset, $sort_field, $sort_dir);
    }

    public function getFacebookAdsReportAllWithHttpInfo($fields = null, $exclude_fields = null, $count = '10', $offset = '0', $sort_field = null, $sort_dir = null)
    {
        $request = $this->getFacebookAdsReportAllRequest($fields, $exclude_fields, $count, $offset, $sort_field, $sort_dir);

        return $this->sendRequest($request);
    }

    public function getFacebookAdReport($outreach_id, $fields = null, $exclude_fields = null)
    {
        return $this->getFacebookAdReportWithHttpInfo($outreach_id, $fields, $exclude_fields);
    }

    public function getFacebookAdReportWithHttpInfo($outreach_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getFacebookAdReportRequest($outreach_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getFacebookAdProductActivityReport($outreach_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $sort_field = null)
    {
        return $this->getFacebookAdProductActivityReportWithHttpInfo($outreach_id, $fields, $exclude_fields, $count, $offset, $sort_field);
    }

    public function getFacebookAdProductActivityReportWithHttpInfo($outreach_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $sort_field = null)
    {
        $request = $this->getFacebookAdProductActivityReportRequest($outreach_id, $fields, $exclude_fields, $count, $offset, $sort_field);

        return $this->sendRequest($request);
    }

    public function getLandingPageReportsAll($fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        return $this->getLandingPageReportsAllWithHttpInfo($fields, $exclude_fields, $count, $offset);
    }

    public function getLandingPageReportsAllWithHttpInfo($fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        $request = $this->getLandingPageReportsAllRequest($fields, $exclude_fields, $count, $offset);

        return $this->sendRequest($request);
    }

    public function getLandingPageReport($outreach_id, $fields = null, $exclude_fields = null)
    {
        return $this->getLandingPageReportWithHttpInfo($outreach_id, $fields, $exclude_fields);
    }

    public function getLandingPageReportWithHttpInfo($outreach_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getLandingPageReportRequest($outreach_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getSurveyReportsAll($fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        return $this->getSurveyReportsAllWithHttpInfo($fields, $exclude_fields, $count, $offset);
    }

    public function getSurveyReportsAllWithHttpInfo($fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        $request = $this->getSurveyReportsAllRequest($fields, $exclude_fields, $count, $offset);

        return $this->sendRequest($request);
    }

    public function getSurveyReport($outreach_id, $fields = null, $exclude_fields = null)
    {
        return $this->getSurveyReportWithHttpInfo($outreach_id, $fields, $exclude_fields);
    }

    public function getSurveyReportWithHttpInfo($outreach_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getSurveyReportRequest($outreach_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getSurveyQuestionReportsAll($outreach_id, $fields = null, $exclude_fields = null)
    {
        return $this->getSurveyQuestionReportsAllWithHttpInfo($outreach_id, $fields, $exclude_fields);
    }

    public function getSurveyQuestionReportsAllWithHttpInfo($outreach_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getSurveyQuestionReportsAllRequest($outreach_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getSurveyQuestionReport($outreach_id, $question_id, $fields = null, $exclude_fields = null)
    {
        return $this->getSurveyQuestionReportWithHttpInfo($outreach_id, $question_id, $fields, $exclude_fields);
    }

    public function getSurveyQuestionReportWithHttpInfo($outreach_id, $question_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getSurveyQuestionReportRequest($outreach_id, $question_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getSurveyQuestionAnswers($outreach_id, $question_id, $fields = null, $exclude_fields = null, $respondent_familiarity_is = null)
    {
        return $this->getSurveyQuestionAnswersWithHttpInfo($outreach_id, $question_id, $fields, $exclude_fields, $respondent_familiarity_is);
    }

    public function getSurveyQuestionAnswersWithHttpInfo($outreach_id, $question_id, $fields = null, $exclude_fields = null, $respondent_familiarity_is = null)
    {
        $request = $this->getSurveyQuestionAnswersRequest($outreach_id, $question_id, $fields, $exclude_fields, $respondent_familiarity_is);

        return $this->sendRequest($request);
    }

    public function getSurveyResponsesAll($outreach_id, $fields = null, $exclude_fields = null, $answered_question = null, $chose_answer = null, $respondent_familiarity_is = null)
    {
        return $this->getSurveyResponsesAllWithHttpInfo($outreach_id, $fields, $exclude_fields, $answered_question, $chose_answer, $respondent_familiarity_is);
    }

    public function getSurveyResponsesAllWithHttpInfo($outreach_id, $fields = null, $exclude_fields = null, $answered_question = null, $chose_answer = null, $respondent_familiarity_is = null)
    {
        $request = $this->getSurveyResponsesAllRequest($outreach_id, $fields, $exclude_fields, $answered_question, $chose_answer, $respondent_familiarity_is);

        return $this->sendRequest($request);
    }

    public function getSurveyResponse($outreach_id, $response_id)
    {
        return $this->getSurveyResponseWithHttpInfo($outreach_id, $response_id);
    }

    public function getSurveyResponseWithHttpInfo($outreach_id, $response_id)
    {
        $request = $this->getSurveyResponseRequest($outreach_id, $response_id);

        return $this->sendRequest($request);
    }

    protected function getFacebookAdsReportAllRequest($fields = null, $exclude_fields = null, $count = '10', $offset = '0', $sort_field = null, $sort_dir = null): Request
    {
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ReportingApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/reporting/facebook-ads';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);
        $this->addQueryParam($queryParams, 'sort_field', $sort_field);
        $this->addQueryParam($queryParams, 'sort_dir', $sort_dir);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getFacebookAdReportRequest($outreach_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($outreach_id, 'outreach_id');

        $resourcePath = '/reporting/facebook-ads/{outreach_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'outreach_id', $outreach_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getFacebookAdProductActivityReportRequest($outreach_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $sort_field = null): Request
    {
        $this->requireParam($outreach_id, 'outreach_id');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ReportingApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/reporting/facebook-ads/{outreach_id}/ecommerce-product-activity';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);
        $this->addQueryParam($queryParams, 'sort_field', $sort_field);

        $this->replacePathParam($resourcePath, 'outreach_id', $outreach_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getLandingPageReportsAllRequest($fields = null, $exclude_fields = null, $count = '10', $offset = '0'): Request
    {
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ReportingApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/reporting/landing-pages';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getLandingPageReportRequest($outreach_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($outreach_id, 'outreach_id');

        $resourcePath = '/reporting/landing-pages/{outreach_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'outreach_id', $outreach_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getSurveyReportsAllRequest($fields = null, $exclude_fields = null, $count = '10', $offset = '0'): Request
    {
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ReportingApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/reporting/surveys';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getSurveyReportRequest($outreach_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($outreach_id, 'outreach_id');

        $resourcePath = '/reporting/surveys/{outreach_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'outreach_id', $outreach_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getSurveyQuestionReportsAllRequest($outreach_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($outreach_id, 'outreach_id');

        $resourcePath = '/reporting/surveys/{outreach_id}/questions';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'outreach_id', $outreach_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getSurveyQuestionReportRequest($outreach_id, $question_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($outreach_id, 'outreach_id');
        $this->requireParam($question_id, 'question_id');

        $resourcePath = '/reporting/surveys/{outreach_id}/questions/{question_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'outreach_id', $outreach_id);
        $this->replacePathParam($resourcePath, 'question_id', $question_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getSurveyQuestionAnswersRequest($outreach_id, $question_id, $fields = null, $exclude_fields = null, $respondent_familiarity_is = null): Request
    {
        $this->requireParam($outreach_id, 'outreach_id');
        $this->requireParam($question_id, 'question_id');

        $resourcePath = '/reporting/surveys/{outreach_id}/questions/{question_id}/answers';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);
        $this->addQueryParam($queryParams, 'respondent_familiarity_is', $respondent_familiarity_is);

        $this->replacePathParam($resourcePath, 'outreach_id', $outreach_id);
        $this->replacePathParam($resourcePath, 'question_id', $question_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getSurveyResponsesAllRequest($outreach_id, $fields = null, $exclude_fields = null, $answered_question = null, $chose_answer = null, $respondent_familiarity_is = null): Request
    {
        $this->requireParam($outreach_id, 'outreach_id');

        $resourcePath = '/reporting/surveys/{outreach_id}/responses';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);
        $this->addQueryParam($queryParams, 'answered_question', $answered_question);
        $this->addQueryParam($queryParams, 'chose_answer', $chose_answer);
        $this->addQueryParam($queryParams, 'respondent_familiarity_is', $respondent_familiarity_is);

        $this->replacePathParam($resourcePath, 'outreach_id', $outreach_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getSurveyResponseRequest($outreach_id, $response_id): Request
    {
        $this->requireParam($outreach_id, 'outreach_id');
        $this->requireParam($response_id, 'response_id');

        $resourcePath = '/reporting/surveys/{outreach_id}/responses/{response_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'outreach_id', $outreach_id);
        $this->replacePathParam($resourcePath, 'response_id', $response_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }
}
