<?php

declare(strict_types=1);

/**
 * ReportsApi
 * PHP version 5.
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mailchimp Marketing API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.80
 * Contact: apihelp@mailchimp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MailchimpMarketing\Api;

use GuzzleHttp\Psr7\Request;

class ReportsApi extends AbstractApi
{
    public function getAllCampaignReports($fields = null, $exclude_fields = null, $count = '10', $offset = '0', $type = null, $before_send_time = null, $since_send_time = null)
    {
        return $this->getAllCampaignReportsWithHttpInfo($fields, $exclude_fields, $count, $offset, $type, $before_send_time, $since_send_time);
    }

    public function getAllCampaignReportsWithHttpInfo($fields = null, $exclude_fields = null, $count = '10', $offset = '0', $type = null, $before_send_time = null, $since_send_time = null)
    {
        $request = $this->getAllCampaignReportsRequest($fields, $exclude_fields, $count, $offset, $type, $before_send_time, $since_send_time);

        return $this->sendRequest($request);
    }

    public function getCampaignReport($campaign_id, $fields = null, $exclude_fields = null)
    {
        return $this->getCampaignReportWithHttpInfo($campaign_id, $fields, $exclude_fields);
    }

    public function getCampaignReportWithHttpInfo($campaign_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getCampaignReportRequest($campaign_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getCampaignAbuseReports($campaign_id, $fields = null, $exclude_fields = null)
    {
        return $this->getCampaignAbuseReportsWithHttpInfo($campaign_id, $fields, $exclude_fields);
    }

    public function getCampaignAbuseReportsWithHttpInfo($campaign_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getCampaignAbuseReportsRequest($campaign_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getCampaignAbuseReport($campaign_id, $report_id, $fields = null, $exclude_fields = null)
    {
        return $this->getCampaignAbuseReportWithHttpInfo($campaign_id, $report_id, $fields, $exclude_fields);
    }

    public function getCampaignAbuseReportWithHttpInfo($campaign_id, $report_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getCampaignAbuseReportRequest($campaign_id, $report_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getCampaignAdvice($campaign_id, $fields = null, $exclude_fields = null)
    {
        return $this->getCampaignAdviceWithHttpInfo($campaign_id, $fields, $exclude_fields);
    }

    public function getCampaignAdviceWithHttpInfo($campaign_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getCampaignAdviceRequest($campaign_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getCampaignClickDetails($campaign_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        return $this->getCampaignClickDetailsWithHttpInfo($campaign_id, $fields, $exclude_fields, $count, $offset);
    }

    public function getCampaignClickDetailsWithHttpInfo($campaign_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        $request = $this->getCampaignClickDetailsRequest($campaign_id, $fields, $exclude_fields, $count, $offset);

        return $this->sendRequest($request);
    }

    public function getCampaignClickDetailsForLink($campaign_id, $link_id, $fields = null, $exclude_fields = null)
    {
        return $this->getCampaignClickDetailsForLinkWithHttpInfo($campaign_id, $link_id, $fields, $exclude_fields);
    }

    public function getCampaignClickDetailsForLinkWithHttpInfo($campaign_id, $link_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getCampaignClickDetailsForLinkRequest($campaign_id, $link_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getSubscribersInfo($campaign_id, $link_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        return $this->getSubscribersInfoWithHttpInfo($campaign_id, $link_id, $fields, $exclude_fields, $count, $offset);
    }

    public function getSubscribersInfoWithHttpInfo($campaign_id, $link_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        $request = $this->getSubscribersInfoRequest($campaign_id, $link_id, $fields, $exclude_fields, $count, $offset);

        return $this->sendRequest($request);
    }

    public function getSubscriberInfo($campaign_id, $link_id, $subscriber_hash, $fields = null, $exclude_fields = null)
    {
        return $this->getSubscriberInfoWithHttpInfo($campaign_id, $link_id, $subscriber_hash, $fields, $exclude_fields);
    }

    public function getSubscriberInfoWithHttpInfo($campaign_id, $link_id, $subscriber_hash, $fields = null, $exclude_fields = null)
    {
        $request = $this->getSubscriberInfoRequest($campaign_id, $link_id, $subscriber_hash, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getDomainPerformanceForCampaign($campaign_id, $fields = null, $exclude_fields = null)
    {
        return $this->getDomainPerformanceForCampaignWithHttpInfo($campaign_id, $fields, $exclude_fields);
    }

    public function getDomainPerformanceForCampaignWithHttpInfo($campaign_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getDomainPerformanceForCampaignRequest($campaign_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getEcommerceProductActivityForCampaign($campaign_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $sort_field = null)
    {
        return $this->getEcommerceProductActivityForCampaignWithHttpInfo($campaign_id, $fields, $exclude_fields, $count, $offset, $sort_field);
    }

    public function getEcommerceProductActivityForCampaignWithHttpInfo($campaign_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $sort_field = null)
    {
        $request = $this->getEcommerceProductActivityForCampaignRequest($campaign_id, $fields, $exclude_fields, $count, $offset, $sort_field);

        return $this->sendRequest($request);
    }

    public function getEepurlActivityForCampaign($campaign_id, $fields = null, $exclude_fields = null)
    {
        return $this->getEepurlActivityForCampaignWithHttpInfo($campaign_id, $fields, $exclude_fields);
    }

    public function getEepurlActivityForCampaignWithHttpInfo($campaign_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getEepurlActivityForCampaignRequest($campaign_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getEmailActivityForCampaign($campaign_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $since = null)
    {
        return $this->getEmailActivityForCampaignWithHttpInfo($campaign_id, $fields, $exclude_fields, $count, $offset, $since);
    }

    public function getEmailActivityForCampaignWithHttpInfo($campaign_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $since = null)
    {
        $request = $this->getEmailActivityForCampaignRequest($campaign_id, $fields, $exclude_fields, $count, $offset, $since);

        return $this->sendRequest($request);
    }

    public function getEmailActivityForSubscriber($campaign_id, $subscriber_hash, $fields = null, $exclude_fields = null, $since = null)
    {
        return $this->getEmailActivityForSubscriberWithHttpInfo($campaign_id, $subscriber_hash, $fields, $exclude_fields, $since);
    }

    public function getEmailActivityForSubscriberWithHttpInfo($campaign_id, $subscriber_hash, $fields = null, $exclude_fields = null, $since = null)
    {
        $request = $this->getEmailActivityForSubscriberRequest($campaign_id, $subscriber_hash, $fields, $exclude_fields, $since);

        return $this->sendRequest($request);
    }

    public function getLocationsForCampaign($campaign_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        return $this->getLocationsForCampaignWithHttpInfo($campaign_id, $fields, $exclude_fields, $count, $offset);
    }

    public function getLocationsForCampaignWithHttpInfo($campaign_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        $request = $this->getLocationsForCampaignRequest($campaign_id, $fields, $exclude_fields, $count, $offset);

        return $this->sendRequest($request);
    }

    public function getCampaignOpenDetails($campaign_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $since = null)
    {
        return $this->getCampaignOpenDetailsWithHttpInfo($campaign_id, $fields, $exclude_fields, $count, $offset, $since);
    }

    public function getCampaignOpenDetailsWithHttpInfo($campaign_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $since = null)
    {
        $request = $this->getCampaignOpenDetailsRequest($campaign_id, $fields, $exclude_fields, $count, $offset, $since);

        return $this->sendRequest($request);
    }

    public function getSubscriberInfoForOpenedCampaign($campaign_id, $subscriber_hash, $fields = null, $exclude_fields = null)
    {
        return $this->getSubscriberInfoForOpenedCampaignWithHttpInfo($campaign_id, $subscriber_hash, $fields, $exclude_fields);
    }

    public function getSubscriberInfoForOpenedCampaignWithHttpInfo($campaign_id, $subscriber_hash, $fields = null, $exclude_fields = null)
    {
        $request = $this->getSubscriberInfoForOpenedCampaignRequest($campaign_id, $subscriber_hash, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getCampaignRecipients($campaign_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        return $this->getCampaignRecipientsWithHttpInfo($campaign_id, $fields, $exclude_fields, $count, $offset);
    }

    public function getCampaignRecipientsWithHttpInfo($campaign_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        $request = $this->getCampaignRecipientsRequest($campaign_id, $fields, $exclude_fields, $count, $offset);

        return $this->sendRequest($request);
    }

    public function getCampaignRecipient($campaign_id, $subscriber_hash, $fields = null, $exclude_fields = null)
    {
        return $this->getCampaignRecipientWithHttpInfo($campaign_id, $subscriber_hash, $fields, $exclude_fields);
    }

    public function getCampaignRecipientWithHttpInfo($campaign_id, $subscriber_hash, $fields = null, $exclude_fields = null)
    {
        $request = $this->getCampaignRecipientRequest($campaign_id, $subscriber_hash, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getSubReportsForCampaign($campaign_id, $fields = null, $exclude_fields = null)
    {
        return $this->getSubReportsForCampaignWithHttpInfo($campaign_id, $fields, $exclude_fields);
    }

    public function getSubReportsForCampaignWithHttpInfo($campaign_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getSubReportsForCampaignRequest($campaign_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function getUnsubscribedListForCampaign($campaign_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        return $this->getUnsubscribedListForCampaignWithHttpInfo($campaign_id, $fields, $exclude_fields, $count, $offset);
    }

    public function getUnsubscribedListForCampaignWithHttpInfo($campaign_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        $request = $this->getUnsubscribedListForCampaignRequest($campaign_id, $fields, $exclude_fields, $count, $offset);

        return $this->sendRequest($request);
    }

    public function getUnsubscribedListMember($campaign_id, $subscriber_hash, $fields = null, $exclude_fields = null)
    {
        return $this->getUnsubscribedListMemberWithHttpInfo($campaign_id, $subscriber_hash, $fields, $exclude_fields);
    }

    public function getUnsubscribedListMemberWithHttpInfo($campaign_id, $subscriber_hash, $fields = null, $exclude_fields = null)
    {
        $request = $this->getUnsubscribedListMemberRequest($campaign_id, $subscriber_hash, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    protected function getAllCampaignReportsRequest($fields = null, $exclude_fields = null, $count = '10', $offset = '0', $type = null, $before_send_time = null, $since_send_time = null): Request
    {
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ReportsApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/reports';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);
        $this->addQueryParam($queryParams, 'type', $type);
        $this->addQueryParam($queryParams, 'before_send_time', $before_send_time);
        $this->addQueryParam($queryParams, 'since_send_time', $since_send_time);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getCampaignReportRequest($campaign_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');

        $resourcePath = '/reports/{campaign_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getCampaignAbuseReportsRequest($campaign_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');

        $resourcePath = '/reports/{campaign_id}/abuse-reports';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getCampaignAbuseReportRequest($campaign_id, $report_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');
        $this->requireParam($report_id, 'report_id');

        $resourcePath = '/reports/{campaign_id}/abuse-reports/{report_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);
        $this->replacePathParam($resourcePath, 'report_id', $report_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getCampaignAdviceRequest($campaign_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');

        $resourcePath = '/reports/{campaign_id}/advice';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getCampaignClickDetailsRequest($campaign_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0'): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ReportsApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/reports/{campaign_id}/click-details';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getCampaignClickDetailsForLinkRequest($campaign_id, $link_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');
        $this->requireParam($link_id, 'link_id');

        $resourcePath = '/reports/{campaign_id}/click-details/{link_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);
        $this->replacePathParam($resourcePath, 'link_id', $link_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getSubscribersInfoRequest($campaign_id, $link_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0'): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');
        $this->requireParam($link_id, 'link_id');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ReportsApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/reports/{campaign_id}/click-details/{link_id}/members';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);
        $this->replacePathParam($resourcePath, 'link_id', $link_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getSubscriberInfoRequest($campaign_id, $link_id, $subscriber_hash, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');
        $this->requireParam($link_id, 'link_id');
        $this->requireParam($subscriber_hash, 'subscriber_hash');

        $resourcePath = '/reports/{campaign_id}/click-details/{link_id}/members/{subscriber_hash}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);
        $this->replacePathParam($resourcePath, 'link_id', $link_id);
        $this->replacePathParam($resourcePath, 'subscriber_hash', $subscriber_hash);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getDomainPerformanceForCampaignRequest($campaign_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');

        $resourcePath = '/reports/{campaign_id}/domain-performance';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getEcommerceProductActivityForCampaignRequest($campaign_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $sort_field = null): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ReportsApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/reports/{campaign_id}/ecommerce-product-activity';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);
        $this->addQueryParam($queryParams, 'sort_field', $sort_field);

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getEepurlActivityForCampaignRequest($campaign_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');

        $resourcePath = '/reports/{campaign_id}/eepurl';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getEmailActivityForCampaignRequest($campaign_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $since = null): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ReportsApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/reports/{campaign_id}/email-activity';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);
        $this->addQueryParam($queryParams, 'since', $since);

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getEmailActivityForSubscriberRequest($campaign_id, $subscriber_hash, $fields = null, $exclude_fields = null, $since = null): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');
        $this->requireParam($subscriber_hash, 'subscriber_hash');

        $resourcePath = '/reports/{campaign_id}/email-activity/{subscriber_hash}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);
        $this->addQueryParam($queryParams, 'since', $since);

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);
        $this->replacePathParam($resourcePath, 'subscriber_hash', $subscriber_hash);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getLocationsForCampaignRequest($campaign_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0'): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ReportsApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/reports/{campaign_id}/locations';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getCampaignOpenDetailsRequest($campaign_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0', $since = null): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ReportsApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/reports/{campaign_id}/open-details';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);
        $this->addQueryParam($queryParams, 'since', $since);

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getSubscriberInfoForOpenedCampaignRequest($campaign_id, $subscriber_hash, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');
        $this->requireParam($subscriber_hash, 'subscriber_hash');

        $resourcePath = '/reports/{campaign_id}/open-details/{subscriber_hash}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);
        $this->replacePathParam($resourcePath, 'subscriber_hash', $subscriber_hash);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getCampaignRecipientsRequest($campaign_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0'): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ReportsApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/reports/{campaign_id}/sent-to';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getCampaignRecipientRequest($campaign_id, $subscriber_hash, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');
        $this->requireParam($subscriber_hash, 'subscriber_hash');

        $resourcePath = '/reports/{campaign_id}/sent-to/{subscriber_hash}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);
        $this->replacePathParam($resourcePath, 'subscriber_hash', $subscriber_hash);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getSubReportsForCampaignRequest($campaign_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');

        $resourcePath = '/reports/{campaign_id}/sub-reports';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getUnsubscribedListForCampaignRequest($campaign_id, $fields = null, $exclude_fields = null, $count = '10', $offset = '0'): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling ReportsApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/reports/{campaign_id}/unsubscribed';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getUnsubscribedListMemberRequest($campaign_id, $subscriber_hash, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($campaign_id, 'campaign_id');
        $this->requireParam($subscriber_hash, 'subscriber_hash');

        $resourcePath = '/reports/{campaign_id}/unsubscribed/{subscriber_hash}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'campaign_id', $campaign_id);
        $this->replacePathParam($resourcePath, 'subscriber_hash', $subscriber_hash);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }
}
