<?php

declare(strict_types=1);

/**
 * RootApi
 * PHP version 5.
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mailchimp Marketing API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.80
 * Contact: apihelp@mailchimp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MailchimpMarketing\Api;

use GuzzleHttp\Psr7\Request;

class RootApi extends AbstractApi
{
    public function getRoot($fields = null, $exclude_fields = null)
    {
        return $this->getRootWithHttpInfo($fields, $exclude_fields);
    }

    public function getRootWithHttpInfo($fields = null, $exclude_fields = null)
    {
        $request = $this->getRootRequest($fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    protected function getRootRequest($fields = null, $exclude_fields = null): Request
    {
        $resourcePath = '/';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }
}
