<?php

declare(strict_types=1);

/**
 * SearchCampaignsApi
 * PHP version 5.
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mailchimp Marketing API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.80
 * Contact: apihelp@mailchimp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MailchimpMarketing\Api;

use GuzzleHttp\Psr7\Request;

class SearchCampaignsApi extends AbstractApi
{
    public function search($query, $fields = null, $exclude_fields = null)
    {
        return $this->searchWithHttpInfo($query, $fields, $exclude_fields);
    }

    public function searchWithHttpInfo($query, $fields = null, $exclude_fields = null)
    {
        $request = $this->searchRequest($query, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    protected function searchRequest($query, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($query, 'query');

        $resourcePath = '/search-campaigns';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);
        $this->addQueryParam($queryParams, 'query', $query);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }
}
