<?php

declare(strict_types=1);

/**
 * SurveysApi
 * PHP version 5.
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mailchimp Marketing API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.80
 * Contact: apihelp@mailchimp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MailchimpMarketing\Api;

use GuzzleHttp\Psr7\Request;

class SurveysApi extends AbstractApi
{
    public function publishSurvey($list_id, $survey_id): void
    {
        $this->publishSurveyWithHttpInfo($list_id, $survey_id);
    }

    public function publishSurveyWithHttpInfo($list_id, $survey_id)
    {
        $request = $this->publishSurveyRequest($list_id, $survey_id);

        return $this->sendRequest($request);
    }

    public function unpublishSurvey($list_id, $survey_id): void
    {
        $this->unpublishSurveyWithHttpInfo($list_id, $survey_id);
    }

    public function unpublishSurveyWithHttpInfo($list_id, $survey_id)
    {
        $request = $this->unpublishSurveyRequest($list_id, $survey_id);

        return $this->sendRequest($request);
    }

    protected function publishSurveyRequest($list_id, $survey_id): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($survey_id, 'survey_id');

        $resourcePath = '/lists/{list_id}/surveys/{survey_id}/actions/publish';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'survey_id', $survey_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams);
    }

    protected function unpublishSurveyRequest($list_id, $survey_id): Request
    {
        $this->requireParam($list_id, 'list_id');
        $this->requireParam($survey_id, 'survey_id');

        $resourcePath = '/lists/{list_id}/surveys/{survey_id}/actions/unpublish';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'list_id', $list_id);
        $this->replacePathParam($resourcePath, 'survey_id', $survey_id);

        return $this->buildRequest('POST', $resourcePath, $queryParams);
    }
}
