<?php

declare(strict_types=1);

/**
 * TemplateFoldersApi
 * PHP version 5.
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mailchimp Marketing API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.80
 * Contact: apihelp@mailchimp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MailchimpMarketing\Api;

use GuzzleHttp\Psr7\Request;

class TemplateFoldersApi extends AbstractApi
{
    public function remove($folder_id): void
    {
        $this->removeWithHttpInfo($folder_id);
    }

    public function removeWithHttpInfo($folder_id)
    {
        $request = $this->removeRequest($folder_id);

        return $this->sendRequest($request);
    }

    public function list($fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        return $this->listWithHttpInfo($fields, $exclude_fields, $count, $offset);
    }

    public function listWithHttpInfo($fields = null, $exclude_fields = null, $count = '10', $offset = '0')
    {
        $request = $this->listRequest($fields, $exclude_fields, $count, $offset);

        return $this->sendRequest($request);
    }

    public function get($folder_id, $fields = null, $exclude_fields = null)
    {
        return $this->getWithHttpInfo($folder_id, $fields, $exclude_fields);
    }

    public function getWithHttpInfo($folder_id, $fields = null, $exclude_fields = null)
    {
        $request = $this->getRequest($folder_id, $fields, $exclude_fields);

        return $this->sendRequest($request);
    }

    public function update($folder_id, $body)
    {
        return $this->updateWithHttpInfo($folder_id, $body);
    }

    public function updateWithHttpInfo($folder_id, $body)
    {
        $request = $this->updateRequest($folder_id, $body);

        return $this->sendRequest($request);
    }

    public function create($body)
    {
        return $this->createWithHttpInfo($body);
    }

    public function createWithHttpInfo($body)
    {
        $request = $this->createRequest($body);

        return $this->sendRequest($request);
    }

    protected function removeRequest($folder_id): Request
    {
        $this->requireParam($folder_id, 'folder_id');

        $resourcePath = '/template-folders/{folder_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'folder_id', $folder_id);

        return $this->buildRequest('DELETE', $resourcePath, $queryParams);
    }

    protected function listRequest($fields = null, $exclude_fields = null, $count = '10', $offset = '0'): Request
    {
        if (null !== $count && $count > 1000) {
            throw new \InvalidArgumentException('invalid value for "$count" when calling TemplateFoldersApi., must be smaller than or equal to 1000.');
        }

        $resourcePath = '/template-folders';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields, $count, $offset);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getRequest($folder_id, $fields = null, $exclude_fields = null): Request
    {
        $this->requireParam($folder_id, 'folder_id');

        $resourcePath = '/template-folders/{folder_id}';
        $queryParams = $this->buildQueryParams($fields, $exclude_fields);

        $this->replacePathParam($resourcePath, 'folder_id', $folder_id);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function updateRequest($folder_id, $body): Request
    {
        $this->requireParam($folder_id, 'folder_id');
        $this->requireParam($body, 'body');

        $resourcePath = '/template-folders/{folder_id}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'folder_id', $folder_id);

        return $this->buildRequest('PATCH', $resourcePath, $queryParams, $body);
    }

    protected function createRequest($body): Request
    {
        $this->requireParam($body, 'body');

        $resourcePath = '/template-folders';
        $queryParams = [];

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }
}
