<?php

declare(strict_types=1);

/**
 * VerifiedDomainsApi
 * PHP version 5.
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mailchimp Marketing API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.80
 * Contact: apihelp@mailchimp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MailchimpMarketing\Api;

use GuzzleHttp\Psr7\Request;

class VerifiedDomainsApi extends AbstractApi
{
    public function createVerifiedDomain($body)
    {
        return $this->createVerifiedDomainWithHttpInfo($body);
    }

    public function createVerifiedDomainWithHttpInfo($body)
    {
        $request = $this->createVerifiedDomainRequest($body);

        return $this->sendRequest($request);
    }

    public function deleteDomain($domain_name): void
    {
        $this->deleteDomainWithHttpInfo($domain_name);
    }

    public function deleteDomainWithHttpInfo($domain_name)
    {
        $request = $this->deleteDomainRequest($domain_name);

        return $this->sendRequest($request);
    }

    public function getDomain($domain_name)
    {
        return $this->getDomainWithHttpInfo($domain_name);
    }

    public function getDomainWithHttpInfo($domain_name)
    {
        $request = $this->getDomainRequest($domain_name);

        return $this->sendRequest($request);
    }

    public function getVerifiedDomainsAll()
    {
        return $this->getVerifiedDomainsAllWithHttpInfo();
    }

    public function getVerifiedDomainsAllWithHttpInfo()
    {
        $request = $this->getVerifiedDomainsAllRequest();

        return $this->sendRequest($request);
    }

    public function submitDomainVerification($domain_name, $body)
    {
        return $this->submitDomainVerificationWithHttpInfo($domain_name, $body);
    }

    public function submitDomainVerificationWithHttpInfo($domain_name, $body)
    {
        $request = $this->submitDomainVerificationRequest($domain_name, $body);

        return $this->sendRequest($request);
    }

    protected function createVerifiedDomainRequest($body): Request
    {
        $this->requireParam($body, 'body');

        $resourcePath = '/verified-domains';
        $queryParams = [];

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }

    protected function deleteDomainRequest($domain_name): Request
    {
        $this->requireParam($domain_name, 'domain_name');

        $resourcePath = '/verified-domains/{domain_name}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'domain_name', $domain_name);

        return $this->buildRequest('DELETE', $resourcePath, $queryParams);
    }

    protected function getDomainRequest($domain_name): Request
    {
        $this->requireParam($domain_name, 'domain_name');

        $resourcePath = '/verified-domains/{domain_name}';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'domain_name', $domain_name);

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function getVerifiedDomainsAllRequest(): Request
    {
        $resourcePath = '/verified-domains';
        $queryParams = [];

        return $this->buildRequest('GET', $resourcePath, $queryParams);
    }

    protected function submitDomainVerificationRequest($domain_name, $body): Request
    {
        $this->requireParam($domain_name, 'domain_name');
        $this->requireParam($body, 'body');

        $resourcePath = '/verified-domains/{domain_name}/actions/verify';
        $queryParams = [];

        $this->replacePathParam($resourcePath, 'domain_name', $domain_name);

        return $this->buildRequest('POST', $resourcePath, $queryParams, $body);
    }
}
