<?php

declare(strict_types=1);

/**
 * ApiException
 * PHP version 5.
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mailchimp Marketing API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.80
 * Contact: apihelp@mailchimp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MailchimpMarketing;

/**
 * ApiException Class Doc Comment.
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */
class ApiException extends \Exception
{
    /**
     * The HTTP body of the server response either as JSON or string.
     */
    public mixed $responseBody {
        get {
            return $this->responseBody;
        }
    }

    /**
     * The HTTP header of the server response.
     *
     * @var null|string[]
     */
    public ?array $responseHeaders {
        get {
            return $this->responseHeaders;
        }
    }

    /**
     * The deserialized response object.
     */
    public mixed $responseObject {
        get {
            return $this->responseObject;
        }
        set {
            $this->responseObject = $value;
        }
    }

    /**
     * Constructor.
     *
     * @param string        $message         Error message
     * @param int           $code            HTTP status code
     * @param null|string[] $responseHeaders HTTP response header
     * @param null|mixed    $responseBody    HTTP decoded body of the server response either as \stdClass or string
     */
    public function __construct(string $message = '', int $code = 0, $responseHeaders = [], $responseBody = null)
    {
        parent::__construct($message, $code);
        $this->responseHeaders = $responseHeaders;
        $this->responseBody = $responseBody;
    }
}
